### PR TITLE
Add basher and cleanup env and language plugins

### PR DESCRIPTION
**Pull request by cornfeedhobo**
- add support for [basher](https://github.com/basherpm/basher/)
- update all the *env plugins to newer conventions
- update all the language plugins to newer conventions
- update tests accordingly

I've been using these locally for a few weeks and have been happy.

It'd be great if someone else ran these locally for a little while and see if they like them.

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
I'll deal with the failing build soon. I uncovered some more stuff I'm dealing with.

**Comment by cornfeedhobo** [comment]
@nwinkler Without digging into the failing test right now, I uncovered a race condition with the *env suite. bash-it is loading everything from the .bash_it directory and not the working directory, causing all *env dependent resources to fail on load.

Test completion file:
```
echo $PWD
goenv versions
```

Output when starting a new shell:
```
/home/cornfeedhobo/.bash_it
goenv: 'go' command not found

The 'go' command exists in these Go versions:
  1.14.7
  1.14.9
```

The only thing I can think of is overhauling bash-it to make sure it's bootstrapping from the working directory, which probably entails making sure we have absolute paths for bash-it. I haven't really dug into core so I'm not sure. Do you have any ideas?

**Comment by cornfeedhobo** [comment]
@nwinkler Confirmed. *env plugins are fixed when I wrap them in `pushd`/`popd`

```shell
pushd "$OLDPWD" &>/dev/null
{ _command_exists go && go version &>/dev/null ; } || return 0

# Wrapper function to iterate, in reverse, through a list of colon
# separated paths to support multiple entries in GOPATH.
function _go_pathmunge_wrap() {
  IFS=':' local -a 'a=($1)'
  local i=${#a[@]}
  while [[ $i -gt 0 ]] ; do
    i=$(( i - 1 ))
    pathmunge "${a[i]}/bin"
  done
}

export GOROOT="${GOROOT:-$(go env GOROOT)}"
export GOPATH="${GOPATH:-$(go env GOPATH)}"
_go_pathmunge_wrap "${GOPATH}:${GOROOT}"
popd &>/dev/null
```

**Comment by NoahGorny** [comment]
@cornfeedhobo wanna continue on this?

**Comment by cornfeedhobo** [comment]
I am, but I'm between laptops and this is going to need a refreshed look. You can close it and I'll deal with it later

**Pull request closed without merging**
