### PR TITLE
adding ability to set theme as a path to specific file

### PR DESCRIPTION
**Pull request by dayne**
I wanted to track my custom theme file in a different repo outside of the .bash_it directory.

This tweak here allows you to set the BASH_IT_THEME to point at the specific theme file you want to use without worry of the putting it into the `.bash_it/themes/(name)/(name).theme.bash` scheme.
Example of my .bashrc for setting the theme using this tweak:
```
# Lock and Load a custom theme file
# location /.bash_it/themes/
#export BASH_IT_THEME='modern'
export BASH_IT_THEME="$HOME/.local/bash_it-theme.bash"
```

### CODE REVIEW

**Comment by nwinkler** [comment]
That's a nice addition! It would be great if you could add some documentation to the project's README.md file to show how to use this. Maybe add a sentence and an example to the https://github.com/Bash-it/bash-it#themes section...

**Comment by tswicegood** [comment]
Super cool! I agree with @nwinkler on adding some docs so folks know how to use this.

**Comment by LanikSJ** [comment]
I can see this being useful for a lot of people.  I'm even willing to write the doc if needed.

**Comment by dayne** [comment]
Thanks all.  I appreciate the enthusiasm for this feature request I've put in. Always fun to run into an enthusiastic and open user community.

I've put forward a recommendation in the pull request for an updated README that gives nod to this feature and an updated bashrc template comment. 

Comments/fixes/clarifications welcomed.  Happy to see this feature be considered.

**Comment by dayne** [comment]
As a follow up - I think adding (and documenting it) contributes to fixing #892

**Comment by nwinkler** [comment]
Thanks - this is great! I might tweak the readme a bit, but thanks for providing the starting point!

**Pull request merged**
