### PR TITLE
gitline: Added support for Deuteranopia and fixed some undescriptive file names.

### PR DESCRIPTION
**Pull request by Zanark**
Added support for Deuternopia color blindness.

The prompt colors can be uncommented from the gitline.theme.bash file. The default colors are the same as the old colors.

### CODE REVIEW

**Comment by Zanark** [comment]
image

Scale used for reference.

**Comment by nwinkler** [comment]
Thanks! Since I feel that making local modifications to themes (or other files in the repo) almost always ends up with trouble, I'd like to suggest a small modification: Can you maybe introduce an environment variable that allows to switch the colors? For example something like this:

```bash
GITLINE_COLOR_SCHEME_DEUTERANOPIA=${GITLINE_COLOR_SCHEME_DEUTERANOPIA:=false}
```

You could then use this flag in your theme to switch to the alternate colors. Ideally, also document the env variable in the theme's readme file.

Thoughts?

**Comment by Zanark** [comment]
Yep that's an amazing idea! I had made these changes in my theme locally when my friend requested for a color change to help him with his Deuteranopia.

I'll work on this and update the PR.

**Comment by nwinkler** [comment]
Great - looking forward to your update here!

**Comment by NoahGorny** [comment]
Gentle ping @Zanark

**Comment by Zanark** [comment]
Apologies for abandoning this PR for so long. Got really busy with work. Will work on this this weekend and update the PR.

**Comment by Zanark** [comment]
I had created this PR to help a friend out who has CB.
He loved the changes I made and suggested a few more too. I'll commit them too.

✌️

**Comment by NoahGorny** [comment]
@zanarak I am closing this, but feel free to reopen if you want to revisit this :smile:

**Pull request closed without merging**
