### PR TITLE
Vendor apm completion

### PR DESCRIPTION
**Pull request by buhl**
As per #1818

## Description
Removed code from `completion/available/apm.completion.bash`
Added https://github.com/vigo/apm-bash-completion as a vendored lib 
and sourced it from `apm.completion.bash`

## Motivation and Context
#1818 and potentially #1819 

## How Has This Been Tested?

I have run the tests locally and enabled/disabled the completion locally as well.

## Types of changes
Vendored apm completion lib

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.

### CODE REVIEW

**Comment by buhl** [comment]
Probably should mention vendored `master`. The version tag pointed to a commit with no license and such.

**Comment by buhl** [comment]
@NoahGorny for when you have the time

**Comment by buhl** [comment]
Should I add
```bash
cite "about-completion"
about-completion "apm completion"
```
at the top of `completion/available/apm.completion.bash`

**Comment by NoahGorny** [comment]
> Should I add
> ```bash
> cite "about-completion"
> about-completion "apm completion"
> ```
> at the top of `completion/available/apm.completion.bash`

Seems like a good idea :smile:

**Comment by cornfeedhobo** [comment]
@buhl you no longer need the `cite` line. I plan to make another PR to remove all of them soon.

**Comment by buhl** [comment]
@NoahGorny  Should be ready now.

**Review by NoahGorny — APPROVED** [review]
Well done @buhl !
Thank you so much :smile:

**Pull request merged**
