### PR TITLE
Clean barbuk theme

### PR DESCRIPTION
**Pull request by BarbUk**
## Description

Add barbuk theme to `clean_files.txt`.
shfmt lint only.

### CODE REVIEW

**Review by cornfeedhobo — APPROVED** [review]
@NoahGorny Heads up; this is the 3rd PR that I've had to re-run the mac 11 job. I'll probably reach out to github support if this persists, but for now, I recommend re-running actions if that's the only failing job.

@BarbUk Looks like you figured out the bug I ran into; `shfmt` must be run a few times to catch all the whitespace issues. I'm reaching out to the owner of `shfmt` to try and figure it out. Thanks so much for sticking with this!

I have verified no code changes using shfmt and diff locally. Approved.

Edit: @NoahGorny After you take a look, I'd recommend Squashing this merge.

**Comment by BarbUk** [comment]
> @BarbUk Looks like you figured out the bug I ran into; shfmt must be run a few times to catch all the whitespace issues.

Yes.

What's strange is that `pre-commit` is telling me that everything is fine, but running shfmt change the file.

For example, from the current master:
```bash
~/.dotfiles/modules/bash-it on  master ⤏  origin •1 ✗ ❯ git diff
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
modified: clean_files.txt
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
@ clean_files.txt:30 @ lint_clean_files.sh
#
themes/90210
themes/powerline
themes/barbuk

# plugins
#

   ~/.dotfiles/modules/bash-it on  master ⤏  origin •1 ✗ ❯ pre-commit run --files `cat clean_files.txt`
Trim Trailing Whitespace....................................................Passed
Fix End of Files............................................................Passed
Check for merge conflicts...................................................Passed
Mixed line ending...........................................................Passed
Check for added large files.................................................Passed
Check for conflict markers and core.whitespace errors.......................Passed
Test shell scripts with shellcheck..........................................Passed
Check shell style with shfmt................................................Passed
CRLF end-lines remover......................................................Passed

   ~/.dotfiles/modules/bash-it on  master ⤏  origin •1 ✗  1.1s ❯ shfmt -w themes/barbuk/barbuk.theme.bash 

   ~/.dotfiles/modules/bash-it on  master ⤏  origin •2 ✗  2.0s ❯ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   clean_files.txt
	modified:   themes/barbuk/barbuk.theme.bash

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by davidpfarrell** [comment]
HI All -  This is a drive-by comment, I have not deeply reviewed the situation, but I noticed:

```
❯ pre-commit run --files `cat clean_files.txt`
```

This is likely not going to do what you think it will ... I don't *believe* that pre-commit will traverse directories given in the `clean_files.txt` file.

That's why`lint_clean_files.sh` actually has logic to traverse the directories and build a file-only list which is passed to pre-commit.

Try running `./lint_clean_files.sh` instead of invoking pre-commit directly.

**Comment by NoahGorny** [comment]
Well done @BarbUk, and thanks for the review @cornfeedhobo @davidpfarrell !

**Comment by BarbUk** [comment]
> Try running ./lint_clean_files.sh instead of invoking pre-commit directly.

This is the correct solution, thanks.

**Pull request merged**
