### PR TITLE
Add clean_files.txt sorting hook

### LINKED ISSUE #1871: Create a CI step that checks that clean_files.txt is sorted alphabetically
I want to create a CI step that checks the order and fails if the order in clean_files.txt is incorrect, can be done by comparing the strings of each section

_Originally posted by @NoahGorny in https://github.com/Bash-it/bash-it/pull/1870#issuecomment-822696349_

### PR DESCRIPTION
**Pull request by NoahGorny**
We now sort clean_files.txt alphabetically!

## Description

Added a hook that checks that the lines in clean_files.txt are sorted alphabetically.
I have splitted the checks into 3 parts- root files, root directories, and non root directories
I also sorted clean_files.txt according to said feedback :smile:

## Motivation and Context

Closes #1871

## How Has This Been Tested?

Locally, by runnnig `lint_clean_files.sh`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by cornfeedhobo — APPROVED** [review]
"Make it so"

**Review by davidpfarrell — APPROVED** [review]
Simple and clever, I like it !

**Comment by NoahGorny** [comment]
Thanks guys, I changed the way we sort to use a compat31 string comparison, so we will achieve backwards compatible and yet consistent way to sort the file, you are welcome to take a look again :smile:

**Review by davidpfarrell — APPROVED** [review]
The compat31 seems great for deterministic sorting across all bash versions.

Q: Did it have any affect on the sorted results?

**Review by cornfeedhobo — APPROVED** [review]

**Comment by NoahGorny** [comment]
> The compat31 seems great for deterministic sorting across all bash versions.
> 
> Q: Did it have any affect on the sorted results?

It did, mainly moved `.` before other entries, like `.gitattribute` or `history.` vs `history-`

Thanks for the review @davidpfarrell and @cornfeedhobo, you rock!

**Pull request merged**
