### PR TITLE
Feature/git changelog

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description
Fixed the git-changelog plugin 

## How Has This Been Tested?
Tested locally, but I insist to test it on your systems

## Screenshots (if appropriate):
image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by tbhaxor** [comment]
The cleanup PR for it can be found here: https://github.com/Bash-it/bash-it/pull/1816

**Comment by nwinkler** [comment]
It looks like #1816 and this PR contain the same changes? This PR seems to contain lots of whitespace/formatting changes in addition to some new code...

**Comment by tbhaxor** [comment]
> It looks like #1816 and this PR contain the same changes? This PR seems to contain lots of whitespace/formatting changes in addition to some new code...

I get that @nwinkler I created two PRs because @NoahGorny asked me to do so [here](https://github.com/Bash-it/bash-it/pull/1787#issuecomment-761566224)

**Comment by nwinkler** [comment]
The way I understood @NoahGorny was that you should open
* one PR with just the cleanup/formatting of the existing code, and
* one PR with the new functionality (but not with the cleanup changes).

The reason for doing that is that both PRs can be reviewed individually, one with just the cleanup/whitespace changes, and one with just the functional changes, without the added noise of the whitespace and formatting changes.

**Comment by tbhaxor** [comment]
@nwinkler I think then closing this pull request is better

**Comment by NoahGorny** [comment]
I am closing this, next time @tbhaxor open one PR with the new feature, and afterwards open one with the lint fixes

**Pull request closed without merging**
