### PR TITLE
added yarn completions

### PR DESCRIPTION
**Pull request by tbhaxor**
This repo is licensed under MIT license. However, I have taken permission from the original author

https://github.com/dsifford/yarn-completion/issues/44

### CODE REVIEW

**Comment by nwinkler** [comment]
As outlined in my comment [here](https://github.com/Bash-it/bash-it/issues/1470#issuecomment-584556474), I'm not a fan of adding more copy/paste code to Bash-it. It will lead to licensing concerns, increased maintenance for out-of-date completion scripts, etc.

The yarn completion repo contains instructions on how to install it into the existing Bash completion infrastructure, I'd prefer that - this would not require to add another copy/paste file to Bash-it.

**Comment by tbhaxor** [comment]
as you wish

**Comment by tbhaxor** [comment]
I would request you to add **Scope of Contribution** so that we could open PRs regarding the same

**Comment by tbhaxor** [comment]
@nwinkler what type of contributions are you expecting? Like regarding themes, plugins, more completions or what else...

**Pull request closed without merging**
