### PR TITLE
24 pull-reqs: Install.sh TLC and enhancements

### PR DESCRIPTION
**Pull request by nickl-**
I stumbled on your project @ http://24pullrequests.com/ but this is not the first time I stumbled across bash-it and have been meaning to give it a try.

On installation I caught a couple of hiccups and since its xmas and all if we need an excuse. I confined myself to install.sh only, I have a habit of getting carried away once I start. Have a look see if you like my work, maybe we do some soon.

The commit comments should be elaborate enough to explain the gists, a quick overview or roadmap of the the journey you're about to take might be in order.

The first commit encompasses code style conformance changes. When I start working on a new project I instinctively absorb the chosen code style so as to adopt its practice and ensure that my additions blend seamlessly. With this project and I mean no disrespect you didn't seem to have a code style. So I attempted to conform to what appears as tho majority used practices.  

@ab4d9fb explains an overview of the strategy I adopted. The commit only changes style so as to enable you to cherry pick at it should you disagree with the normalisation. 

Your journey will continue through the sites I've secured and or enhanced to make the installation more robust to users like me who don'n read instructions while at the same time not changing a thing. It still does exactly the same things you originally expected from it.
- Package home folder remains ~/.bash_it
- Back up is made of .bash_profile
- Option to create jekyll config.
- 3 times extensions/plugins installation.

If nothing changed how did it take 14 commits you might ask:
- Script location detection allowing the possibility that someone might run `install.sh` from somewhere other than ~/.bash_it and deals with it
- Dealing with the possibility that there is no .bash_profile as well as the chance that a backup already exists called .bash_profile.bak and deal with it
- Ensure that we do end up having a package home  ~/.bash_it
- Several usability enhancements like one char select at the y/n prompt 
- The grand finale - addition of direct install functionality using bash and curl to fetch the install script from github and proceed with the installation as before.
- Code comments added
- Documentation updated to reflect the new changes, even though none of us reads it anyway =) 

nJoy

### CODE REVIEW

**Comment by gaelicWizard** [comment]
What's the news on this 9-year-old PR? Some of these fixes are still needed and I have reimplemented a few already on my branch...

**Comment by NoahGorny** [comment]
I like the easy install part, and the cleanup- but this needs a rebase.
I am also unsure about the whole backup thing as I want to ship `bash-it profile` instead.

If this will get rebased with the cleanup and the option to run the install as an easy-setup that would be pretty cool

**Comment by gaelicWizard** [comment]
> Some of these fixes are still needed

Looks like there's only a few that are still needed, mainly unbound parameters, string quoting, and reduced subshells and external binaries. I guess I've already submitted new PRs with most of these anyway.

**Comment by nickl-** [comment]
I have absolutely no idea what happened to stay and what got dumped, this was ridiculously long ago. Here in is rebased for what it's worth.

nJoy!

**Pull request closed without merging**
