### PR TITLE
Adds dirstack segment to powerline themes

### PR DESCRIPTION
**Pull request by davidpfarrell**
Adds a new segment to the powerline themes to show the `pushd` level.

Shows only the character if there's just one entry in the stack, else shows the character and the depth.

I'm not sold on either the default color nor the default character and would be happy to discuss alternatives.

-DF

### CODE REVIEW

**Comment by nwinkler** [comment]
Hi, thanks for all the contributions! Sorry about the delay, work and life got in the way the last couple of weeks...

I'll take a look at your PRs in the next couple of days, promised! I'm currently working through the backlog of PRs that have piled up...

**Comment by davidpfarrell** [comment]
> Hi, thanks for all the contributions! Sorry about the delay, work and life got in the way the last couple of weeks...
> 
> I'll take a look at your PRs in the next couple of days, promised! I'm currently working through the backlog of PRs that have piled up...

Hey @nwinkler thanks for the note.

Several of my PRs may require updates due other PRs being merged.

I'm happy to update them, but might wait until you have a chance to review the individual PRs and confirm if the changes they represent are something you'll consider merging.

If there's a change you're not likely to merge anyway, then no need updating the PR.

I personally use all of these PRs in my personal prompt configuration, so if you end up not feeling comfortable making them part of the official powerline prompts, I'll likely fork powerline into a custom prompt and submit that.

I do think they are useful and could benefit all powerline users, so I would prefer they get merged there if possible.

Thanks again and please let me know if you have any questions or concerns!

-DF

**Comment by nwinkler** [comment]
Hi @davidpfarrell - thanks for the kind words!

I want to merge the changes, just haven't found the time to do it so far.

If it's not too much work for you, could you please rebase the PRs on the current version?

General question: Do your PRs build up on each other? Do you need to rebase the PRs once I have merged the first one? If so, please let me know which one to look at first, and I'll get started with that...

Thanks for your patience, and again sorry for the delays in getting this looked at...

**Comment by davidpfarrell** [comment]
> General question: Do your PRs build up on each other? Do you need to rebase the PRs once I have merged the first one? If so, please let me know which one to look at first, and I'll get started with that...

Hi @nwinkler - The PR's don't build on each other but some might need to be updated after others get merged

For tracking purposes (for both of us): Here's the order I think my PRs are best considered in:

1)  #1448 "Makes all powerline vars configurable"
2) #1450 "Fixes prompt bg color on powerline naked theme"
3) #1446 "Adds SHORT_USER/HOSTNAME support to powerline themes"
4) #1443 "Adds shlvl segment to powerline themes"
5) #1442 "Adds dirstack segment to powerline themes"
6) #1444 "Adds history + command line number to powerline themes"
7)  #1445 "Adds soft-separator support to powerline main + multiline themes"
8) #1449 "Adds last segment prompt char to powerline default theme"
9) #1447 "Adds compact support to powerline themes"

These are in the order of least complexity.

I've also posted this list as a comment on #1448 which has been rebased in preparation for merge.

I'll rebase the others as we move through them.

Thanks again,

-DF

**Comment by nwinkler** [comment]
OK - thanks for the patience! I've merged the first three - please rebase #1443 and I'll continue with the merges...

**Comment by nwinkler** [comment]
This one seems to be next, needs to be rebased as well...

**Comment by davidpfarrell** [comment]
> This one seems to be next, needs to be rebased as well...

Rebase is complete, thanks !

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
