### PR TITLE
Bash 3

### PR DESCRIPTION
**Pull request by ikari7789**
Removed usage of += which is unsupported on bash versions < 3.1.
Fixed regex in comparison which is unsupported on bash versions < 3.1
Fixed sed regex switch which is not the same on all systems.

### CODE REVIEW

**Comment by nwinkler** [comment]
Which operating systems are you using that have Bash < 3.1? Just curious...

**Comment by ikari7789** [comment]
Unfortunately, CentOS 4. I'm dealing with some rather legacy servers :/
Up to you to decide whether or not to merge this. Not sure if worth it or not, but was just putting it out there.

**Comment by thedrow** [comment]
I don't think we should support such old versions. It will be overwritten anyway when we update the completion script from upstream.

**Comment by nwinkler** [comment]
Agree with @thedrow - I'm going to close this. If you really want, you can keep these changes in your own fork and use that on your servers...

**Pull request closed without merging**
