### PR TITLE
Updated vagrant bash completion

### PR DESCRIPTION
**Pull request by thedrow**
This PR updates the vagrant bash completion to the latest commit https://github.com/kura/vagrant-bash-completion/commit/e720d90ae9a6589eb13c578b40a503e902d4897c

### CODE REVIEW

**Comment by thedrow** [comment]
Any idea why the build is failing?

**Comment by nwinkler** [comment]
@ipoval Do you know why the Travis build keeps failing from time to time?

The error is 

```
not ok 3 plugins base: myip()
# (in test file test/plugins/base.plugin.bats, line 26)
#   `[[ $mask_ip == 'Your public IP is: ?.?.?.?' ]]' failed
```

**Comment by thedrow** [comment]
Can I merge this anyway?

**Comment by nwinkler** [comment]
Sure, the tests are note related to this.

**Comment by ipoval** [comment]
@nwinkler , let me put ignore statement into that test, my guess would be that `myip()` function has network latency and from time to time it times-out

**Comment by nwinkler** [comment]
Thanks!

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
