### PR TITLE
Update base.theme.bash

### PR DESCRIPTION
**Pull request by aashah**
Fix support for recognizing git when in submodules and the regression when in subdirectories of a git repository.

### CODE REVIEW

**Comment by wendorf** [comment]
Thanks for finding that subdirectory regression and fixing it, @aashah ! I've tested this fix as well and it looks good from here. The broken output we were seeing was:

```
 |2.1.6|ruby 2.1.6p336 mymachine in ~/workspace/repo/src/subdirectory
○ →
```

when we should see:

```
ruby 2.1.6p336 mymachine in ~/workspace/repo/src/subdirectory
± dw |master ?:1 ✗| →
```

(note it is in "src/subdirectory" instead of "src/submodule")

**Comment by nwinkler** [comment]
Thanks!

**Comment by edubxb** [comment]
Great, thanks! :smile:

**Comment by brayanrl2603-ops** [comment]
> ¡Genial, gracias! 😄

**Pull request merged**
