### PR TITLE
Short aliases for `git commit --amend` (bang)

### PR DESCRIPTION
**Pull request by bittner**
## Description

With a bang (!) character we can make amending a commit intuitively dangerous.

## Motivation and Context

The idea is taken from Oh-My-Zsh, https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git

## How Has This Been Tested?

I use those aliases for years on my developer laptop. I just made the identical changes to a fresh installation of bash-it on my developer machine. They work as expected. 

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by bittner** [comment]
The failing of the `CI / lint` job is likely unrelated to the changes introduced in this PR. – Go error: `undefined: any`

**Comment by bittner** [comment]
This would be a nice enhancement of the Git aliases. Please, merge!

**Comment by cornfeedhobo** [comment]
@bittner Could you `rebase` or `amend`, then `push`? The CI runs are too old to re-run.

**Comment by bittner** [comment]
> @bittner Could you `rebase` or `amend`, then `push`? The CI runs are too old to re-run.

Done. CI jobs all pass. Ready for merging?

**Comment by cornfeedhobo** [comment]
@davidpfarrell @NoahGorny @gaelicWizard Any interest to weigh in here? This introduces the `!` suffix. I'm inclined to merge because I've already said I don't think we should be managing these and thus have little opinion on what conventions should be followed. Please let me know soon :)

**Comment by bittner** [comment]
Note that the bang is inspired by OMZ, hence we're harmonizing with the other framework, which I think is considered a good idea judging from other discussions in this repo.

Please go ahead. I created several PRs for git-aliases, so that integrating them can get discussed in depth. But it should also allow to speed up merging okay-PRs.

If there are no objections, please don't wait any longer. Press the button. Thank you!

**Comment by bittner** [comment]
Can we merge this minor enhancement?

**Comment by bittner** [comment]
Is there any chance to get this PR merged? 🙏

**Pull request merged**
