### PR TITLE
Show NodeJS version in Powerline themes

### PR DESCRIPTION
**Pull request by edubxb**
Currently, only nvm is supported.

Making Bash-it more front-end development friendly 😉.

### CODE REVIEW

**Comment by nwinkler** [comment]
This is great - thanks! Could you please add the new `node` segment to the Powerline theme's README file?

(Sorry about the delay, work and life got in the way the last couple of weeks...)

**Comment by edubxb** [comment]
Sure.

**Comment by edubxb** [comment]
Being honest, I forgot to update the docs :sweat:

**Comment by nwinkler** [comment]
Thanks!!!!

**Pull request merged**
