### PR TITLE
Show Git root on prompt

### PR DESCRIPTION
**Pull request by ritola**
- Show Git root folder name when SCM_THEME_ROOT_SUFFIX is set
- Default is off

### CODE REVIEW

**Comment by ritola** [comment]
I've added functionality to show Git root folder name on the prompt. This is useful when working multiple git repositories, and if the prompt is set to show only the last path of the directory tree.

**Comment by nwinkler** [comment]
Great - can you please add a section in the readme on this? The other `SCM_` options are explained there as well, it would be good to have something on this new option there as well.

**Comment by miketheman** [comment]
#triage 

@ritola This appears to have stalled - there was a request to update the README for docs, and the base.theme.bash has changed enough since this writing that the PR is not immediately mergable.

Is this something still needed, or has it been covered by the introduction of the `SCM_GIT_`?

**Comment by ritola** [comment]
Sorry! I missed the first message. I'll rebase this and review README. Thanks a lot for reminding.

**Comment by NoahGorny** [comment]
@ritola still want to take a stab at this?

**Pull request closed without merging**
