### PR TITLE
Bash it master

### PR DESCRIPTION
**Pull request by jimwhimpey**

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
@nwinkler I have no idea how this popped up to the top of the PR list today, but I'm going to guess someone opened this for their own purposes (pull the `.diff` or `.patch` endpoint maybe?). I'm going to guess this is safe to close.

**Comment by jimwhimpey** [comment]
My mistake! Sorry.

**Comment by cornfeedhobo** [comment]
@jimwhimpey No problem! I figured this was a mistake PR.

**Comment by nwinkler** [comment]
Yeah, that's a weird one - thanks for noticing!

**Pull request closed without merging**
