### PR TITLE
completion/wpscan: simplify code flow (whitespace)

### PR DESCRIPTION
**Pull request by gaelicWizard**
## Description
Convert from indented if-block to return then unindented code. This should have basically one line change at the top, one line removed at the bottom, and then all whitespace.

## Motivation and Context
Just cleaning up.

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by davidpfarrell — APPROVED** [review]
Confirmed mostly just the early bailout, whitespace adjustments.

BUT also fixing array to be an actual  array.

cc:  @tbhaxor I think you and I broke this in #1898 where $_opt_ became the entire OPTS string ...

I'm going tentatively mark as approved but would like @tbhaxor to chime in before merging ...

**Comment by gaelicWizard** [comment]
I've rebased on current master, and changed `"` to `'` for the `$OPTS` array.

**Comment by davidpfarrell** [comment]
Q: Can we be adding this to `clean_files.txt` ?

**Comment by gaelicWizard** [comment]
> Q: Can we add this to `clean_files.txt` ?
> 
> [edit] Grammar

Already is! 👍

**Review by davidpfarrell — APPROVED** [review]

**Pull request merged**
