### PR TITLE
Updated AWS plugin

### PR DESCRIPTION
**Pull request by edubxb**
- Fixed export option to work in Mac (I think)
- Added remove option
- Other minor changes

### CODE REVIEW

**Comment by edubxb** [comment]
Seems that the Mac fix don't work, so I need to change the code again :_(

**Comment by edubxb** [comment]
Ready for merge!

**Comment by edubxb** [comment]
@nwinkler, @tswicegood can you validate this PR and proceed with the merge?

Thanks!

**Comment by nwinkler** [comment]
Sorry, I can't really verify this, since I'm not using AWS...

**Comment by edubxb** [comment]
@nwinkler no problem, thanks!

**Comment by edubxb** [comment]
This is working fine, so I will proceed to merge this PR.

**Pull request merged**
