### PR TITLE
Added redline theme, based on powerline

### PR DESCRIPTION
**Pull request by dnoiz1**
added redline, a powerline based theme

### CODE REVIEW

**Comment by nwinkler** [comment]
Can you share a screenshot of what this looks like?

Also - would it be possible to make some of this functionality available in the `powerline` theme? That theme's `base` file is used by all of the `powerline-*`  themes, and it would be nice to avoid code duplication if possible.

**Comment by dnoiz1** [comment]
sure - when i started i didnt want to taint powerline (it was a rushed effort)
I'll install it on a rhel7.3 vm and take a screenshot all color coordinated

I havent tested:
- ruby ps1
- extended scm
- vim
- battery

just crossing my fingers that they already work :)

**Comment by dnoiz1** [comment]
ok have merged base with powerline, updated readme, added screenshot, squashed commits,

**Comment by tswicegood** [comment]
Haven't tried it yet, but just checked out the screenshot. That looks really great! Thanks for the contribution.

-----

Thinking aloud: it looks like we're really close to having a generic "*line" theme. We ought to add a `monoline` theme that's just a grayscale version of `redline`, then create multiple colors for various themes. If we set all of the colors with only if they aren't set we could even allow for complete control by the user at the `.base_profile` level if they wanted to customize them.

^^ not necessary for this to be merged by any stretch of the imagination though. Could be something for us to tackle as a separate PR.

**Comment by tswicegood** [comment]
Just tried this. I'm seeing unicode `?` boxes at the separators for some reason. I even tried using the `nerd-font` repo linked in the README and got the same thing. I don't see this on the powerline themes with the hacked fonts they recommend. Any idea what's up? 

fullscreen_1_27_17__1_46_pm

**Comment by dnoiz1** [comment]
@tswicegood 
which terminal emulator are you using?

interesting, you're displaying  `PROMPT_CHAR` `\xe0b0` but not `\xe0bc`
both `PROMPT_CHAR` and  `POWERLINE_LEFT_SEPARATOR` should be in fonts https://github.com/ryanoasis/nerd-fonts#powerline-extra-symbols

the other glyphs are from included sets.

the repo for the font I linked also includes requirements for patching the glyphs into other fonts

**Comment by tswicegood** [comment]
Doh! I can't believe I let this one sit this long. Glad to see you're keeping it in-sync @dnoiz1 and sorry for the delay.

I just gave it a try again on brand new box and am still seeing those unicode boxes. I did verify that `powerline` works as expected. My `$TERM` is `xterm-256color`, not sure if that is any help. Would love to get this merged, but the error seems reproducible as this is a clean macOS install with a fresh install of bash-it.

**Comment by tswicegood** [comment]
Doh! I should read the README. :-D

Just installed the nerd-font version of the font you're using and everything works fine. Gonna merge this in. Thanks for sticking with it for so long!!

🎉

**Comment by dnoiz1** [comment]
Lolol

I use it, so like I thought I should update it, thanks for merging lol

**Comment by edubxb** [comment]
After merging this PR, the [sudo mode](https://github.com/Bash-it/bash-it/tree/master/themes/powerline#user-information) for the user info segment no longer works

**Comment by tswicegood** [comment]
@edubxb looks like [this change][1] is the problem. I think if we add this to that file we can solve the issue:

```bash
USER_INFO_SUDO_CHAR="!"
```

Can you give it a go and let me know?

[1]: https://github.com/Bash-it/bash-it/compare/d318c65...0d3eedbc1c9980729e58f28ae2c3b66188bc5571#diff-b6a92a872755615a2d17245bfba10dfcL28

**Comment by edubxb** [comment]
Algo, the variable:

**Comment by edubxb** [comment]
This PR https://github.com/Bash-it/bash-it/pull/1117 has the fixes.

**Comment by tswicegood** [comment]
Thanks, @edubxb!

**Pull request merged**
