### PR TITLE
theme/atomic: Update sudo check method

### PR DESCRIPTION
**Pull request by davidpfarrell**
Per discussion and changes made in #1535, applying simplified sudo check to `atomic` theme.

Tested locally.

-DF

---

CC: @lfelipe1501 , @buhl

### CODE REVIEW

**Comment by lfelipe1501** [comment]
nice 👍

**Comment by BarbUk** [comment]
I don't understand the usage of `sudo -vn`.
Is it to check if the user is root or to detect if the user is using sudo ?

If it's to detect if the user is root, why not use `whoami` ?
Here are some benchmarks:
```
 ~ ❯ time for _ in {1..1000}; do sudo uptime | grep "load" >/dev/null; done

real	0m16.992s
user	0m16.817s
sys	0m6.967s

 ~ ❯ time for _ in {1..1000}; do whoami >/dev/null 2>&1; done

real	0m1.859s
user	0m1.665s
sys	0m0.446s

 ~ ❯ time for _ in {1..1000}; do id -u >/dev/null 2>&1; done

real	0m26.534s
user	0m26.971s
sys	0m2.109s

 ~ ❯ time for _ in {1..1000}; do sudo -vn >/dev/null 2>&1; done

real	0m9.104s
user	0m6.190s
sys	0m3.730s
```

If it's to check if the user is using sudo, the check fails with any other user than root.
I.e., if I use sudo to impersonate www-data user:
```bash
sudo -u www-data -s -H
```

**Comment by BarbUk** [comment]
@davidpfarrell Using `sudo -vn` also leaves traces in the system log.
See: https://github.com/Bash-it/bash-it/pull/1535#issuecomment-606890316

**Comment by davidpfarrell** [comment]
Hi @BarbUk 

> I don't understand the usage of `sudo -vn`

Lifted from [Previous Discussion](https://github.com/Bash-it/bash-it/issues/1460#issuecomment-566670741) :

The purpose of the check is to confirm `"Do I have an active sudo session, whereby if I entered a sudo command it would not ask me for my password"`.

Several themes have a component whereby they give an indicator if you have cached sudo credentials.

Here's an example of powerline's sudo check in action:

sudo_test

Hope that helps!

-DF

**Comment by BarbUk** [comment]
> The purpose of the check is to confirm "Do I have an active sudo session, whereby if I entered a sudo command it would not ask me for my password".

Ok, so it's a different use-case than root detection.
I ran some checks, and `sudo -vn` is the best performing option.

Thank you for explaining :)

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
