### PR TITLE
New customization options

### PR DESCRIPTION
**Pull request by edubxb**
Added two new variables:

POWERLINE_LEFT_END
POWERLINE_RIGHT_END

used to change the end character of the the left and right parts.

### CODE REVIEW

**Comment by nwinkler** [comment]
Great idea! Want to add some documentation in the theme's README for the new options?

**Comment by edubxb** [comment]
I will do it in another PR, updating the README for some Powerline themes, after checking it, there are some _customization_ options don't documented, also adding [Nerd Fonts](http://nerdfonts.com/) as an alternative to Powerline fonts, because have more **cool** icons to customize the prompt.

image

**Comment by tswicegood** [comment]
Ok, now I wanna go update my prompt to use lego fonts…

**Comment by edubxb** [comment]
Nerd fonts have a lot of icons more semantic that Powerline, so is easier to understand the information the prompts is showing to the user, this is the main reason I'm suggesting it.

**Comment by nwinkler** [comment]
Awesome - looking forward to your update!

**Pull request merged**
