### PR TITLE
Emperor theme; features time on the prompt with different colors for eac...

### PR DESCRIPTION
**Pull request by mimoralea**
...h quater of the hour

### CODE REVIEW

**Comment by nwinkler** [comment]
Can you add a screenshot of the new theme to this PR? We'll add it to the Wiki showing the different themes.

**Comment by mimoralea** [comment]
emperor-top-of-the-hour

**Comment by mimoralea** [comment]
early-10

**Comment by mimoralea** [comment]
yellow

**Comment by mimoralea** [comment]
Let me know if this works.

**Comment by nwinkler** [comment]
Thanks, looks good to me!

**Comment by mimoralea** [comment]
Good deal.

**Pull request merged**
