### PR TITLE
Add url manipulation plugin

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description

Added the plugin to handle the URL related workload and slugify function to add handle the heading to slug transformation.

## Motivation and Context

While writing the headings of the blog or documentation on the markdown for the project, I need to go to external services to create the slug for the heading. This is very unproductive, so I have created the plugin for handling such transforms in the terminal.

## How Has This Been Tested?

Locally on Linux

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by tbhaxor** [comment]
@NoahGorny Ping

**Comment by tbhaxor** [comment]
@NoahGorny Ping 0x02

**Comment by tbhaxor** [comment]
@davidpfarrell any idea why macos test is passing here but failed in #2192 ?

Also I tried on macos ventura (13.2) it is passing

**Review by seefood — APPROVED** [review]
Looks legit.

**Pull request merged**
