### PR TITLE
Add alias gmv

### PR DESCRIPTION
**Pull request by icanhazstring**
This will enable the ability to rename a branch using bash-it git alias

### CODE REVIEW

**Comment by nwinkler** [comment]
Thanks!

**Comment by icanhazstring** [comment]
your welcome :)

**Comment by apaatsio** [comment]
I know I'm a bit late for this train, but I think `gmv` is a bad choice for this alias. I think it's too easy to confuse it with the `git mv` command. Moreover, it does not follow the naming scheme of the other `git branch` aliases that are all named `gb*`.

IMO, the name `gbm` would be better alias for `git branch -m` than `gmv`.

**Comment by icanhazstring** [comment]
@apaatsio this is actually a valid point. Sorry i missed that. If @nwinkler is fine with it, I would change it with another PR.

**Comment by nwinkler** [comment]
Yes, that makes sense - please create another PR for fixing this, and I'll merge.

@apaatsio Thanks for catching this!

**Comment by icanhazstring** [comment]
There we go: https://github.com/Bash-it/bash-it/pull/937

@apaatsio Thanks for pointing that out!

**Pull request merged**
