### PR TITLE
Add support for active gcloud account in powerline prompt

### PR DESCRIPTION
**Pull request by ofirshtrull**
## Description
I have a situation that I have 3 clients all in GCP 
and I'm constantly changing between accounts  and I thought maybe I can add a prompt vizualtion like with aws 
so here it is

## Motivation and Context

look at the description :-)

## How Has This Been Tested?
I tested it on my mac 

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by davidpfarrell — APPROVED** [review]
This looks legit !

Kudos for adding a core function in base so other themes could easily add their own version of the prompt.

**Comment by ofirshtrull** [comment]
@davidpfarrell the only upgrade i couldn't find is to add the googke or gcp logo insted of the (g) in front of the active account name maybe

**Comment by davidpfarrell** [comment]
> @davidpfarrell the only upgrade i couldn't find is to add the goog[l]e or gcp logo insted of the (g) in front of the active account name maybe

Searching [NerdFonts](https://www.nerdfonts.com/cheat-sheet) for `"google_cloud"` yielded this:

Screen Shot 2021-03-11 at 2 25 58 PM

here's the character for copy/pasting:



Its likely not present in the default powerline font, but should be available to any nerd-font user.

Since its (probably) not in the powerline font, I'm not sure if its a good idea to make it the default character.

Probably best to leave a standard ascii/unicode character as default, but you could add the a note in the docs on how to override the character (and maybe link to nerdfonts) as I'm sure other nerds out there would like to use it, too :)

**Comment by ofirshtrull** [comment]
@davidpfarrell I think I will just leave the (G)  to support everyone

**Comment by NoahGorny** [comment]
well done @ofirshtrull  :smile:

**Pull request merged**
