### PR TITLE
Clean flutter completions

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description

Formats the file with shfmt

## Motivation and Context

Clean bashit from #1696 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by cornfeedhobo — APPROVED** [review]
Nice and simple. Thanks!

**Review by cornfeedhobo — CHANGES_REQUESTED** [review]
Looks like you still have a failing test. Blocking because I approved to quickly.

**Comment by tbhaxor** [comment]
> Looks like you still have a failing test. Blocking because I approved to quickly.

Seems like this issue is not fixed yet. @NoahGorny did you manage to find the fix?

**Review by NoahGorny — APPROVED** [review]
Thank you @tbhaxor !

**Pull request merged**
