### PR TITLE
`init - bash` it's automatically load auto-completion

### PR DESCRIPTION
**Pull request by sptndc**

### CODE REVIEW

**Comment by nwinkler** [comment]
Sorry, but what is the purpose of this PR?

**Comment by sptndc** [comment]
I'm just trying to make a script it simpler.

**Comment by sptndc** [comment]
Hi @nwinkler sorry for my answer, but I understand what you mean.

I have already told via commit message that `jenv`, `nodenv`, `plenv`, `pyenv`, `rbenv` with the `init - bash` command that automatically loads auto-completion, you does not need to check whether completions exists or not and then uses ` source`.

**Comment by nwinkler** [comment]
OK, got it - sorry for the confusion. I must confess that I did not understand what you were trying to do from your initial commit message - might have been the language barrier.

Thanks for the additional explanation, that helped a lot.

**Comment by sptndc** [comment]
Yes, maybe because of language barriers.

No problem. :+1:

**Pull request merged**
