### PR TITLE
Added SQLMap Completions

### PR DESCRIPTION
**Pull request by tbhaxor**

### CODE REVIEW

**Comment by tbhaxor** [comment]
@nwinkler plz review this

**Comment by nwinkler** [comment]
Hi, thanks for the contribution!

It looks like this is pretty much a copy of this code here, right? http://www.korznikov.com/2014/12/bash-tab-completion-for-awesome-tool.html

Did you clear this with the author? I did not see any licensing/copyright information on his blog...

**Comment by tbhaxor** [comment]
Idk i found it somewhere else and i found most of the part are same. I will rather include the author name here

**Comment by tbhaxor** [comment]
On safe side i have added new commit :laughing:

**Comment by nwinkler** [comment]
Thanks

**Pull request merged**
