### PR TITLE
Fixed opening vim

### PR DESCRIPTION
**Pull request by dracorp**
Fix for https://github.com/Bash-it/bash-it/issues/1030

### CODE REVIEW

**Comment by nwinkler** [comment]
This looks good - thanks! Before I merge this, could you please provide one or two sentences as to what this change is doing and why it's fixing the vim issue?

**Comment by dracorp** [comment]
Of course. For example vim.aliases.bash provides alias v=/usr/bin/vim. Command `complete -p /usr/bin/vim` from **alias-completion.plugin.bash** returns empty string(as *$new_completion*). So to a tmpfile, which will be sourced on the end, goes " v"(*$alias_name*), because:
```
new_completion="${new_completion%` *} $alias_name"
echo "$new_completion" >> "$tmp_file"
```
The v is alias for /usr/bin/vim so vim is invoked. But why vim was invoked in [szymonpk](https://github.com/Bash-it/bash-it/issues/1030#issuecomment-377957142) I don't know. Maybe probably in the same way.

**Comment by nwinkler** [comment]
Got it, thanks for the explanation! You're basically checking whether that command has a valid completion defined, and don't include it in the new completion script if it does not have a completion - that makes sense.

Thanks for fixing this - nice!

**Comment by szymonpk** [comment]
Thanks @dracorp, this PR fixed $EDITOR issue for me as well.

**Pull request merged**
