### PR TITLE
Implement basic encrypt/decrypt using openssl

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description

This pull request implements plugin and aliases for handling encryption or decryption of the file or text payload.

## Motivation and Context

I have to work with encryption daily for saving and retrieving my password or other secrets in a secure container. And I am too lazy for such things, so implemented helpers.

## How Has This Been Tested?

Locally on the Linux

## Screenshots (if appropriate):

Screenshot_20220621_142306
Screenshot_20220621_142226

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by tbhaxor** [comment]
@NoahGorny Ping

**Comment by tbhaxor** [comment]
@NoahGorny Can we remove **bats-test (macos-10.15)** and **bats-test (ubuntu-18.04)** from merge requirements?

**Comment by tbhaxor** [comment]
@NoahGorny Ping 0x02

**Comment by tbhaxor** [comment]
@NoahGorny @davidpfarrell @gaelicWizard Ping 0x03

**Comment by cornfeedhobo** [comment]
@tbhaxor I'm sorry that this went neglected for so long. I think this is best suited for a dedicated project. You could use the [qrush/sub](https://github.com/qrush/sub) repo as a baseline and that way you have everything nice and compartmentalized. I just did something similar with [`bash-trash`](https://github.com/cornfeedhobo/bash-trash).

I'm going to close this for now for the purpose of limiting bloat, but we can always re-open it if people feel differently.

**Pull request closed without merging**
