### PR TITLE
github: Add pr template

### PR DESCRIPTION
**Pull request by NoahGorny**
## Description

Adding a issue and PR templates will help newcomers understand how to contribute to Bash it

## Motivation and Context

I felt like having no template is leaving the repo a bit unorganized, and felt its an appropriate change.

### CODE REVIEW

**Comment by NoahGorny** [comment]
@nwinkler @cornfeedhobo @davidpfarrell what do you think about this one?

**Comment by nwinkler** [comment]
Great idea! For the `issue` template - we should probably add a section where people can post the following in case of an issue:

* Bash config file (`~/.bashrc` or `~/.bash_profile`)
* List of enabled Bash-it plugins/aliases/completions

These are helpful for troubleshooting. Probably don't need them for simple questions, but for bugs these might be helpful.

**Comment by NoahGorny** [comment]
@nwinkler see now

**Comment by cornfeedhobo** [comment]
Just tossing this out there..

If we'd like to differentiate issue creation flows and templates, I suggest checking out the [configuring-the-template-chooser docs](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser).

Also might be worth looking at the [settings app](https://github.com/apps/settings).

**Comment by NoahGorny** [comment]
@cornfeedhobo this seems like a great idea, migrated the issue template changes to #1740 
This PR will only be about the PR template

About the settings app, I am unsure.. I think that settings should be changed by us easily, and require CR/conformation only if its something big. Lemme know what you think :smile:

**Comment by cornfeedhobo** [comment]
@NoahGorny Yeah I don't know how I feel about the settings app. I don't think we need it right now, but just threw it out there in case you were interested.

**Comment by NoahGorny** [comment]
@nwinkler @davidpfarrell @cornfeedhobo take a look now, I reworded some of the final check-boxes

**Comment by cornfeedhobo** [comment]
I like it. thanks!

**Pull request merged**
