### PR TITLE
Add support for AWS Tools Profile.

### PR DESCRIPTION
**Pull request by billmoritz**
http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

### CODE REVIEW

**Comment by edubxb** [comment]
I think that the base plugin is not the correct place for this.

Check the [AWS plugin](https://github.com/Bash-it/bash-it/blob/master/plugins/available/aws.plugin.bash) please.

**Comment by billmoritz** [comment]
If thats true then I don't understand the design pattern. Especially when you take a look at battery_char() which is defined in base. If someone includes battery_char() in a theme and the plugin isn't there it returns nothing. If I was to define aws_profile() in the plugin and a theme used it without having the plugin enabled, you would get an error every prompt.

**Comment by nwinkler** [comment]
I think the `base` theme is the right place for this. @edubxb, did you confuse the `base` theme (where @billmoritz added this change) with the `base` plugin? I agree that the base plugin wouldn't be the right location, but since this is primarily going to be used in themes, the `base` theme looks like the right location for this functionality.

**Comment by edubxb** [comment]
@nwinkler you're right, I confused the base theme with the base plugin :sweat_smile:

**Comment by nwinkler** [comment]
@edubxb Don't worry - I had to look twice as well to see the difference...

**Pull request merged**
