### PR TITLE
Add echo/printf aliases

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
## Description
Add new several `echo`/`printf` aliases where each alias consists of first two letters of each word.

## Motivation and Context
The goal is to simplify alias memorizing without breaking backward compatibility.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by davidpfarrell** [comment]
Greetings !

Your description appears to be copied from the yarn PR:
> Add new several **yarn** aliases where each alias consists of first two letters of each word.

I'm really not sure how useful these alias would be - You would **never** use them from within a bash script as a script can't guarantee the aliases are defined.

And I don't know if `echo` or `printf` are used on the command line enough to warrant the aliases.

I think the risk would be higher that someone might get too used to the aliases and accidentally break their scripts without realizing it.

**Comment by EmilySeville7cfg** [comment]
We can disable them by default. Thanks! :)

**Comment by tbhaxor** [comment]
I do agree with @davidpfarrell here. Till now I haven't required shortcut for echo and printf.

**Comment by gaelicWizard** [comment]
I hate to agree with @davidpfarrell 😉, but I do agree. I just don't see the utility for these. Alsö, the hard-to-foresee consequences of aliases (captured by function definitions) makes me want to avoid any aliases without obvious utility.

**Pull request closed without merging**
