### PR TITLE
themes/agnoster : Port from oh-my-bash

### PR DESCRIPTION
**Pull request by Kreyren**
Initial commit of agnoster theme.

Credit: Isaac "Agnoster" Wolkerstorfer https://github.com/agnoster - original creator

Credit: Kenny Root https://gist.github.com/kruton/8345450 converted from 
zsh to bash

Credit: Toan Nguyen https://github.com/nntoan published in 
ohmybash/oh-my-bash (https://github.com/ohmybash/oh-my-bash)

Credit: https://github.com/speedenator patch for kruton's work and maintainance.

Credit: Hanish K H Updated & fixed on oct-05-2017

### CODE REVIEW

**Comment by Kreyren** [comment]
Commit works on my system, but code quality is poor.

Mergable? Fixing spellcheck with low priority since this is managed by upstream.

This issue is port from `oh-my-bash`

**Comment by nwinkler** [comment]
Can you please remove the image file from your branch (and squash so it gets removed from history)? Don't want to add images to the repo since they will add unnecessary bloat.

**Comment by Kreyren** [comment]
> and squash so it gets removed from history

Recommends squashing it through github GUI so that history of changes to commit is kept.

Squashing on demand if proposed is not sufficient.

**Comment by Kreyren** [comment]
Squashing to save time

**Comment by Kreyren** [comment]
it passes travis now, sorry for pebcak

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
