### PR TITLE
added youtube completion

### PR DESCRIPTION
**Pull request by tbhaxor**
#1295 

Added bash completion for youtube-dl

### CODE REVIEW

**Comment by nwinkler** [comment]
The file you added pretty much looks like 1:1 copy from the [youtube-dl repo's completion file](https://github.com/rg3/youtube-dl/blob/c3bcd206eb031de30179c88ac7acd806a477ceae/devscripts/bash-completion.in) - I really don't want to duplicate this here.

When you install youtube-dl, it should automatically install its own Bash completion script into your Bash environment (at least this happened for me on macOS with Homebrew - the completion is in `/usr/local/etc/bash_completion.d`). From there, you can load it using the `system` completion component in Bash-it - does this work for you?

**Comment by tbhaxor** [comment]
@nwinkler I agree what you say
but its not Cross Platform

in my OS youtube completion is stored in `/usr/etc/bash_completion.d/youtube-dl.bash-completion`

**Comment by tbhaxor** [comment]
This PR may help newbies to enable completions from bashit framework easily :smile:

**Comment by tbhaxor** [comment]
So i am closing this PR right now

**Pull request closed without merging**
