### PR TITLE
added sdk(man) completion and plugin

### PR DESCRIPTION
**Pull request by ancho**
Adds the gvm completion script from my gist https://gist.github.com/ancho/661870a65d79057a33e7 and a plugin to load the gvm environment.

### CODE REVIEW

**Comment by thedrow** [comment]
Is this the groovy version manager or the go version manager?
Both are named the same.

**Comment by ancho** [comment]
Oh. I mean the groovy environment manager https://github.com/gvmtool/gvm-cli/ . Yes.
I didn't know that another tool by the same name exists.

I'll rename the script and plugin to _gvmtool.completion.bash_ and _gvmtool.plugin_ for now.
Until another name evolves :) 
https://github.com/gvmtool/gvm-cli/issues/312

**Comment by ancho** [comment]
gvmtool has been renamed to sdkman for a while now. The completion script and plugin was adjusted.

**Comment by nwinkler** [comment]
Great - thanks! I had to take a look at the date of the original PR before I noticed that this was more than year old :smile:

**Comment by ancho** [comment]
:+1:  No Problem :)

**Pull request merged**
