### PR TITLE
easy theme added

### PR DESCRIPTION
**Pull request by Titivoot**
## Description

New theme added
## Screenshots (if appropriate):
Screenshot_2021-02-28-11-38-14-94

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by NoahGorny** [comment]
Hey @Titivoot, thanks for contributing!

Can you please add your new file to clean_files.txt in order to lint it?

Another important thing is to add some documentation about your theme, because it is a simple one, you can just resort into adding it to the list of screenshots in our documentation. You can store the screenshot itself in our `gh-pages` branch :smile:

Let me know if you need any help!

**Comment by Titivoot** [comment]
@NoahGorny 
Check shell style with shfmt................................................Failed
What am I doing wrong?

**Comment by NoahGorny** [comment]
> @NoahGorny 
> Check shell style with shfmt................................................Failed
> What am I doing wrong?
> 

You need to run `shfmt` on your code in order to format it, try installing it and use it by running `lint_clean_files.sh`

**Comment by Titivoot** [comment]
@NoahGorny 
Ok, I have fixed it, is there anything I need to do?

**Comment by NoahGorny** [comment]
> @NoahGorny 
> Ok, I have fixed it, is there anything I need to do?

Well done!
The only thing I'm thinking could be useful is to add a screenshot of the theme to the docs. Check out the `gh-pages` branch and the list of themes page in the docs for reference :smile:

**Comment by NoahGorny** [comment]
@Titivoot I saw that you indeed opened a PR, good job!!  
The only thing that is missing is linking and adding the picture to the docs, this can be done in `docs/themes-list/index.rst`.  See the other themes and do just like them. Remember that they are sorted alphabetically.

I am impressed by your efforts, keep up the good work!

**Comment by NoahGorny** [comment]
gentle ping @Titivoot

**Pull request merged**
