### PR TITLE
Update preexec.bash

### PR DESCRIPTION
**Pull request by LanikSJ**
This will address the issue in #1278.  This is just a copy and paste and very rough draft I might need help with this one.

### CODE REVIEW

**Comment by nwinkler** [comment]
Thanks for providing this! This looks like a major change (I know that it's copy/paste from a different project, but still). A couple of questions:
* How can we validate that this didn't break anything and everything still works as expected? I'm more than happy to help with validating, but would need some better understanding about how to see whether this is working. Is this primarily used with the `xterm` plugin?
* I wonder whether there's a better way than copy/paste for using this. It would be great if this code could be pulled in as a dependency, but then that would probably make the installation process more complex...

**Comment by LanikSJ** [comment]
I was thinking of using my branch to test with.  I can test with it and hopefully the OP who reported this could test as well to see if anything is broken.

I was thinking of doing a submodule but it might get a bit tricky as we'd have to link to the bash script we want.  Not to mention we'll need to update and carry the entire repo as part of bash-it.  I'm open for suggestions on how to best do this.

**Comment by nwinkler** [comment]
Agreed, a submodule might work, but will be a good deal of overhead for the installation - there's a dozen things that could go wrong, and we'll probably end up with lots of bug reports about things not working. I would obviously want to avoid that...

Let me know if there's anything I can/should test - I'm not using iTerm2 though, I'm using the regular Terminal.app on macOS.

**Comment by LanikSJ** [comment]
I did some testing today I'm still seeing this:
```
iTerm2 Shell Integration not installed.

Your shell has 'extdebug' turned on.
This is incompatible with shell integration.
Find 'shopt -s extdebug' in bash's rc scripts and remove it.
```

@gnachman do you know when does the ITerm2 Shell Integration get loaded (sequence wise) even though I have the command inside my `.bashrc` it still complains that it's not being loaded.  This is after enabling the xterm plugin in Bash-it.  Disabling the plugin removes the message.

**Comment by gnachman** [comment]
I recommend to put it last in .bashrc. Look for `source ~/.iterm2_shell_integration.bash`.

**Comment by LanikSJ** [comment]
The placement where you load `.iterm2_shell_integration.bash` doesn't seem to matter I get the same message.  I'll take a look at the `~/.iterm2_shell_integration.bash`.

**Comment by LanikSJ** [comment]
@nwinkler I had to rename the functions inside `preexec.bash` since this fork uses different function names.  I also added an obligatory line in the file noting this revision was modified for Bash-it.  If there's more that needs to be done for attribution let me know.

@gnachman Thanks for your help looks like my test are passing.  Just basic stuff like enable the plugin and open new iTerm tabs / windows.  Would be awesome if more people besides me can try this branch. To reproduce all I had to do was run `bash-it enable plugin xterm` then close ITerm and open it again.  Opening new tabs / windows does the trick as well.

Let me know if there's any questions or anything I can do to help test this further.

FWIW I'm on iTerm 3.2.7beta3.

**Comment by nwinkler** [comment]
@LanikSJ Can you please describe why you had to rename the functions to make it work with Bash-it? I just want to understand why this was necessary to work - doing this will cause further support/maintenance work down the road with future updates.

Ideally, we would just use the "official" preexec code without modifications, otherwise, we'll run into the same issue with the next update of the library.

**Comment by LanikSJ** [comment]
If you don't rename all the functions and attempt to load Bash-it you'll get a nice little error `preexec_install: command not found` I don't remember the exact wording but Bash-it fails to load all the functions inside `preexec.bash`.

The update is still going to be a problem as it's all manual unfortunately.  I'll volunteer to keep it up to date. 🙂

**Comment by spkane** [comment]
@nwinkler Sorry for the long delay on getting around to looking at this again. I tried the PR and did not see any difference. This did not seem to break anything or make anything specific to my original issue better.

Extraterm currently checks for preexec already being used and therefore simply doesn't enable it's own integrations, but that is unfortunate. I'm not actively using extraterm because of this issue, although I am intrigued by some of it's functionality.

**Comment by buhl** [comment]
I am testing this as well in my [preexec](https://github.com/buhl/bash-it/commits/preexec) branch. It seems to works great with xterm. I added a plugin that rings a bell when long running processes ends and I modified the xterm plugin to use the new preexec.

**Comment by nwinkler** [comment]
@buhl Thanks for the comment! When you say that you replaced the `preexec.bash` file with a different one, did you mean copy/paste? I'd like to avoid copy/paste work due to licensing issues - we should try to find a way to include it as a dependency.

Would like to hear more about your approach. Unfortunately, I probably can't test any of this, since I'm running macOS...

**Comment by buhl** [comment]
@nwinkler You're welcome :)

Well for my own use I just downloaded it and replace the file with the one from @rcaloras repository.
`curl https://github.com/rcaloras/bash-preexec/raw/master/bash-preexec.sh > preexec.bash`

Off the top of my head I think I would make a script for bash-it to fetch @rcaloras preexec script and licensing info. I could then be run when you or any other person wants to test a newer version of the script against bash-it. I could try to add such a script to my branch so you get an idea of what I am thinking.
This would be a manual step every time you wanted to pull in a new version, but I think that is better than fiddling with sub(modules|trees) in git which is almost always a pain...

Let me know if I should write the bash-preexec script. and if so where to put it in bash-it, maybe in./scripts?

**Comment by nwinkler** [comment]
This is a good suggestion. The general issue is that on one hand, I'm not a huge fan of copy/paste of other projects' licensed code, but on the other hand, Bash-it does not contain a real dependency management system. Using Git submodules/subtrees is a kinda ugly workaround, like you said...

A script sounds like a good approach - we could extend the same to other similar cases. For the license file, we might want to pull that into a subdirectory called "third-party-licenses" or something like that, possibly with a separate subdirectory per component.

**Comment by buhl** [comment]
We could adopt a vendor/<libname>/(source and licens files) folder structure?

I have been looking at the source code. And i haven't been able to find the place the preexec lib is sources. Could you help by pointing me in the right direction?

**Comment by davidpfarrell** [comment]
Not sure how I feel about this PR overall, but I thought I could help answer this:

> I have been looking at the source code. And i haven't been able to find the place the preexec lib is source[d]. Could you help by pointing me in the right direction?

I think you'll find it in [bash-it.sh (line:29)](https://github.com/Bash-it/bash-it/blob/master/bash_it.sh#L29) :

_source all libs (except appearance)_
```bash
# libraries, but skip appearance (themes) for now
LIB="${BASH_IT}/lib/*.bash"
APPEARANCE_LIB="${BASH_IT}/lib/appearance.bash"
for _bash_it_config_file in $LIB
do
  if [ "$_bash_it_config_file" != "$APPEARANCE_LIB" ]; then
    # shellcheck disable=SC1090
    source "$_bash_it_config_file"
  fi
done
```

**Comment by buhl** [comment]
> Not sure how I feel about this PR overall, but I thought I could help answer this:
No worries. I will give it a shot. And if it's not something the projects wants we can just close the PR unmerged.
Is there anything I can address that will give you a more clear feeling about this?

**Comment by buhl** [comment]
I have updated my branch as per my suggestions.
I don't know if I should make a separate PR - I don't want to step on anybodies toes. 

https://github.com/buhl/bash-it/commits/preexec

I have made a vendor folderand moved preexec.bash from lib to there.
I have made a make file that can download the source and lincens files.

I don't know if it's better to git clone the hole repository and then removing the .git folder or maybe making it into a git subtree still with the make file to help update it.
Also I don't know if it should be a bash script instead of a make file.

I appreciate any comments on this as I am not completely happy with the solution.

**Pull request closed without merging**
