### PR TITLE
Updated git completion

### LINKED ISSUE #299: Update bash completion for git
I just wanted to change a git remote url as I noticed "git remote se<tab>" brought me set-head but not set-url

I think https://github.com/git/git/blob/master/contrib/completion/git-completion.bash should be a good source.

regards
Steven

### PR DESCRIPTION
**Pull request by thedrow**
This PR updates the git bash completion to https://github.com/git/git/commit/6b1258b07b8ad5671f36bf7e998e905a0142c223.
Fixes #299.

### CODE REVIEW

**Comment by thedrow** [comment]
The build passes.
Any objections?

**Comment by nwinkler** [comment]
Not from my side - feel free to merge...

**Comment by edubxb** [comment]
Thanks!

**Comment by tswicegood** [comment]
:tada:

**Pull request merged**
