### PR TITLE
Add support to change the order of the prompt info in the Powerline Multiline theme

### PR DESCRIPTION
**Pull request by edubxb**
Closes https://github.com/Bash-it/bash-it/issues/485

### CODE REVIEW

**Comment by nwinkler** [comment]
Very cool - what configuration needs to be done to swap the prompt components? Any environment variables or the like?

**Comment by edubxb** [comment]
An environment variable that contains an array that defines the order of the "segments" you want to show.

I'm not sure where to explain this feature, is a theme option, so the Wiki is the best place, I think.

I need to fix some things before merge.

**Comment by nwinkler** [comment]
Yes, agreed, the Wiki might be the best place for documenting this. Other than that, we might think about adding a separate `README.md` file in each theme's folder. This file could include information about the theme, including possible configuration options.

**Comment by tswicegood** [comment]
:+1: to adding a README for the theme. The wiki isn't always immediately available, but they should have all of the bash-it files.

**Comment by edubxb** [comment]
Sorry for leaving this PR unattended so long, but I finally finished.

Only the README.md is missing for now.

**Comment by edubxb** [comment]
README.md added, as my english is not the best, a review is very welcome :smile_cat:

**Comment by edubxb** [comment]
Now any prompt segment can be placed anywhere, at left or at right (README has been update too).

Also, I made a big code refactor, I've changed some names, to make the naming more consistent, I think that all is working fine...

So, this PR is now ready to merge.

**Comment by nwinkler** [comment]
Wow, this looks great! I won't have time to give this a full try today, I'll try to find some time on the weekend.

**Comment by edubxb** [comment]
Thanks! @nwinkler

**Comment by nwinkler** [comment]
Just tried this, works fine for me! Thanks for doing this!

**Comment by nwinkler** [comment]
I've made some changes to the Powerline-Multiline readme in #653 - mostly minor spelling and formatting.

**Pull request merged**
