### PR TITLE
Fix duplicate declaration of `grm`, update `grb<*>`

### LINKED ISSUE #2160: [Bug]: Duplicate declaration of `grm` in git.aliases.bash
### Expected behavior

After having activated the Git aliases, `grm` should do the same as `git rm`.

### Current behavior

`grm` is an alias for `git rebase`. This is because the [alias is redeclared](https://github.com/Bash-it/bash-it/blob/master/aliases/available/git.aliases.bash#L125-L131) after the first `grm`.

### Possible solution

1. Clarify what `grm`, `grmi`, `grma` are meant to be. Why are they (thought to be) intuitive to use?
2. Decide whether to use different aliases for them (i.e. `git rebase`, e.g. based on `grb`) or for `git rm`.

### Context

I attempted to remove a file with Git.

### Steps to reproduce

1. Install the latest version of Bash-it and activate git-aliases.
2. Run `grm` on a file in a repository.

The file will not be removed, but an error message of `git rebase` will appear.

### Bash-it version

dev (Current git SHA: d770030 on 2022-08-17T07:17:42+03:00)

### List of enabled plugins, themes and aliases

general, git

### Bash version

GNU bash, version 5.1.16(1)-release (x86_64-pc-linux-gnu)

### Operating system and version

Ubuntu 22.04.1 LTS jammy (on WSL 2)

### bash-it doctor output

```
$ bash-it doctor
DEBUG: core: main: Loading libraries(except appearance)...
DEBUG: lib: colors: Loading library file...
DEBUG: lib: command_duration: Loading library file...
DEBUG: lib: helpers: Loading library file...
DEBUG: lib: history: Loading library file...
DEBUG: lib: log: Loading library file...
DEBUG: lib: preexec: Loading library file...
DEBUG: lib: preview: Loading library file...
DEBUG: lib: search: Loading library file...
DEBUG: lib: utilities: Loading library file...
DEBUG: core: reloader: Loading all enabled components...
DEBUG: aliases: general: Loading component...
DEBUG: aliases: general: Command 'gshuf' does not exist
DEBUG: aliases: general: Loaded.
DEBUG: aliases: git: Loading component...
DEBUG: aliases: git: Loaded.
DEBUG: plugin: base: Loading component...
DEBUG: plugin: base: Command 'markdown' does not exist
DEBUG: plugin: base: Command 'mkisofs' does not exist
DEBUG: plugin: base: Loaded.
DEBUG: completion: system: Loading component...
DEBUG: completion: system: Loaded.
DEBUG: completion: bash-it: Loading component...
DEBUG: completion: bash-it: Loaded.
DEBUG: completion: aliases: Loading component...
DEBUG: completion: aliases: Loaded.
DEBUG: core: main: Loading theme 'redline'.
DEBUG: core: main: Loading custom aliases, completion, plugins...
DEBUG: core: main: Loading general custom files...
DEBUG: custom: example: Loading custom file...
DEBUG: core: main: Command 'gloobus-preview' does not exist
```

### Your ~/.bashrc

```bash
#!/usr/bin/env bash

# If not running interactively, don't do anything
case $- in
  *i*) ;;
    *) return;;
esac

# Path to the bash it configuration
export BASH_IT="/home/bittner/.bash_it"

# Lock and Load a custom theme file.
# Leave empty to disable theming.
# location /.bash_it/themes/
export BASH_IT_THEME='redline'

# Some themes can show whether `sudo` has a current token or not.
# Set `$THEME_CHECK_SUDO` to `true` to check every prompt:
#THEME_CHECK_SUDO='true'

# (Advanced): Change this to the name of your remote repo if you
# cloned bash-it with a remote other than origin such as `bash-it`.
# export BASH_IT_REMOTE='bash-it'

# (Advanced): Change this to the name of the main development branch if
# you renamed it or if it was changed for some reason
# export BASH_IT_DEVELOPMENT_BRANCH='master'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='https://git.example.com'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set this to the location of your work or project folders
BASH_IT_PROJECT_PATHS="/mnt/c/Users/foobarbaz/projects"

# Set this to false to turn off version control status checking within the prompt for all themes
export SCM_CHECK=true
# Set to actual location of gitstatus directory if installed
#export SCM_GIT_GITSTATUS_DIR="$HOME/gitstatus"
# per default gitstatus uses 2 times as many threads as CPU cores, you can change this here if you must
#export GITSTATUS_NUM_THREADS=8

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)


# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# If your theme use command duration, uncomment this to
# enable display of last command duration.
#export BASH_IT_COMMAND_DURATION=true
# You can choose the minimum time in seconds before
# command duration is displayed.
#export COMMAND_DURATION_MIN_SECONDS=1

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh
```

### Notes

_No response_

### PR DESCRIPTION
**Pull request by bittner**
## Description
Consolidates the `git rebase` aliases thus fixing the unintended overloading of `grm`. `gdel` is outphased as an unclear, non-intuitive sibling of `gbD` (git branch --delete --force).

## Motivation and Context
`grm` is an alias for `git rebase` due to being [redeclared](https://github.com/Bash-it/bash-it/blob/master/aliases/available/git.aliases.bash#L125-L131) after the first `grm` (git rm). The redeclaration is a bug.

Closes #2160.

## How Has This Been Tested?
n/a

## Screenshots (if appropriate):
n/a

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by bittner** [comment]
This PR is a follow-up on #2183, which was accidentally closed. See there for clarifications, as the changes were discussed in depth.

The failing of the lint job is unrelated to the changes introduced in this PR.

**Comment by bittner** [comment]
This PR fixes a bug. The changes have been extensively discussed.

The only thing missing it someone to press the <kbd>Merge</kbd> button. Please? :pray:

**Comment by bittner** [comment]
Can anyone clarify why for macos-11 tests are skipped, which makes the test job fail? 52 tests are skipped: (3 + 46 + 3)
- 16-18 (alias-completion)
- 19-64 (completion bash-it)
- 71-73 (uninstall)

<details><summary>Log excerpt (macos-11)</summary>

```
...
ok 15 bash-it: load enabled aliases from old structure, without priorities
ok 65 install: verify that the install script exists
...
ok 70 install: verify that the template is appended
ok 74 lib composure: _composure_keywords()
...
```

</details>

<details><summary>Skipped tests (macos-11)</summary>

```
ok 16 alias-completion: See that aliases with double quotes and brackets do not break the plugin
ok 17 alias-completion: See that aliases with single quotes and brackets do not break the plugin
ok 18 alias-completion: See that having aliased rm command does not output unnecessary output
ok 19 completion bash-it: ensure that the _bash-it function is available
ok 20 completion bash-it: doctor - show options
ok 21 completion bash-it: help - show options
ok 22 completion bash-it: help - aliases v
ok 23 completion bash-it: update - show options
ok 24 completion bash-it: update - show optional flags
ok 25 completion bash-it: search - show no options
ok 26 completion bash-it: migrate - show no options
ok 27 completion bash-it: show options
ok 28 completion bash-it: bash-ti - show options
ok 29 completion bash-it: shit - show options
ok 30 completion bash-it: bashit - show options
ok 31 completion bash-it: batshit - show options
ok 32 completion bash-it: bash_it - show options
ok 33 completion bash-it: profile - show options
ok 34 completion bash-it: profile load - show options
ok 35 completion bash-it: show - show options
ok 36 completion bash-it: enable - show options
ok 37 completion bash-it: enable - show options a
ok 38 completion bash-it: disable - show options
ok 39 completion bash-it: disable - show options a
ok 40 completion bash-it: disable - provide nothing when atom is not enabled
ok 41 completion bash-it: disable - provide all when atom is not enabled
ok 42 completion bash-it: disable - provide the a* aliases when atom is enabled with the old location and name
ok 43 completion bash-it: disable - provide the a* aliases when atom is enabled with the old location and priority-based name
ok 44 completion bash-it: disable - provide the a* aliases when atom is enabled with the new location and priority-based name
ok 45 completion bash-it: disable - provide the docker-machine plugin when docker-machine is enabled with the old location and name
ok 46 completion bash-it: disable - provide the docker-machine plugin when docker-machine is enabled with the old location and priority-based name
ok 47 completion bash-it: disable - provide the docker-machine plugin when docker-machine is enabled with the new location and priority-based name
ok 48 completion bash-it: disable - provide the todo.txt-cli aliases when todo plugin is enabled with the old location and name
ok 49 completion bash-it: disable - provide the todo.txt-cli aliases when todo plugin is enabled with the old location and priority-based name
ok 50 completion bash-it: disable - provide the todo.txt-cli aliases when todo plugin is enabled with the new location and priority-based name
ok 51 completion bash-it: enable - provide the atom aliases when not enabled
ok 52 completion bash-it: enable - provide the a* aliases when not enabled
ok 53 completion bash-it: enable - provide the a* aliases when atom is enabled with the old location and name
ok 54 completion bash-it: enable - provide the a* aliases when atom is enabled with the old location and priority-based name
ok 55 completion bash-it: enable - provide the a* aliases when atom is enabled with the new location and priority-based name
ok 56 completion bash-it: enable - provide the docker* plugins when docker-compose is enabled with the old location and name
ok 57 completion bash-it: enable - provide the docker-* plugins when docker-compose is enabled with the old location and priority-based name
ok 58 completion bash-it: enable - provide the docker-* plugins when docker-compose is enabled with the new location and priority-based name
ok 59 completion bash-it: enable - provide the docker* completions when docker-compose is enabled with the old location and name
ok 60 completion bash-it: enable - provide the docker* completions when docker-compose is enabled with the old location and priority-based name
ok 61 completion bash-it: enable - provide the docker* completions when docker-compose is enabled with the new location and priority-based name
ok 62 completion bash-it: enable - provide the todo.txt-cli aliases when todo plugin is enabled with the old location and name
ok 63 completion bash-it: enable - provide the todo.txt-cli aliases when todo plugin is enabled with the old location and priority-based name
ok 64 completion bash-it: enable - provide the todo.txt-cli aliases when todo plugin is enabled with the new location and priority-based name
```
```
ok 71 uninstall: verify that the uninstall script exists
ok 72 uninstall: run the uninstall script with an existing backup file
ok 73 uninstall: run the uninstall script without an existing backup file
```

</details>

Is this relevant and needs fixing, or is this an operational error or a flaky test suite?

**Comment by cornfeedhobo** [comment]
@bittner I don't have an answer for why the macos tests do this, but it is my understanding that yes, they need fixing.

**Comment by bittner** [comment]
Can we first merge all the other git-alias related PRs? My hope is that after rebasing onto those changesets that run successfully PRs like this one either succeed (by magic, i.e. we have flaky tests) or the reasons will become clearer.

**Pull request merged**
