### PR TITLE
Docs migrate themes

### PR DESCRIPTION
**Pull request by NoahGorny**
After #1703

### CODE REVIEW

**Comment by nwinkler** [comment]
Please see the comment I left in #1703 - I noticed that this PR contains a couple of screenshots that have somehow made it into the repo at one point in the past. Not sure we have a good way of removing them from the repo's history. (I probably missed them when reviewing the respective PRs way back...)

Anyway, it's not a pattern I want to see us establishing, let's try to keep screenshots and the like out of the repo as much as possible...

**Comment by NoahGorny** [comment]
I agree, yet I think we can keep two mistakenly added pictures

**Comment by nwinkler** [comment]
Yes, agreed. That train has left the station...

**Comment by NoahGorny** [comment]
I will merge this as well, as I want our `readthedocs` to be our only source of documentation, in order to avoid confusion

**Pull request merged**
