### PR TITLE
Add bash-it restart command

### PR DESCRIPTION
**Pull request by NoahGorny**
This command will re exec the shell, yet `cd` to the prev `pwd`
I briefly floated the idea in https://github.com/Bash-it/bash-it/issues/1665#issuecomment-706459916
I still did not test this on Mac, and also I could not enable the `--login` option, as I wanted to run command after shell initialization. @ahmadassaf could you please test this and tell me if this works on Mac?

### CODE REVIEW

**Comment by nwinkler** [comment]
Just tried this on my MacBook, looks good to me:

image

Seems to work just fine.

**Comment by NoahGorny** [comment]
> Just tried this on my MacBook, looks good to me:
> 
> image
> 
> Seems to work just fine.

Thats great! I think this is a great addition to the set of abilities `bash it` has.
I want to merge this, what do you say @nwinkler :smile:

**Comment by nwinkler** [comment]
Agreed - this looks good! Thanks for adding this!

I'm wondering whether we want to include this in the documentation. I've checked the main README file, it currently does not provide a complete list of all commands (e.g. `bash-it reload`). We might want to add that at one point - probably as a separate PR when (hopefully at one point) rework the documentation.

**Comment by NoahGorny** [comment]
> Agreed - this looks good! Thanks for adding this!
> 
> I'm wondering whether we want to include this in the documentation. I've checked the main README file, it currently does not provide a complete list of all commands (e.g. `bash-it reload`). We might want to add that at one point - probably as a separate PR when (hopefully at one point) rework the documentation.

Created a new issue, in the meantime, I think we can merge this (and then #1626)

**Comment by nwinkler** [comment]
Merged! Thanks again for the work you put into this!

I'll let you handle #1626...

**Pull request merged**
