### PR TITLE
plugin/battery: bug fix

### PR DESCRIPTION
**Pull request by NariyasuHeseri**
When `upower --enumerate | grep -i BAT` returns multiple lines of results (which are file paths),
the added quotation (from commit 3cb5f3f7e66345a329cae8ad112f1ecbedc60dab) concatenates them all to provide an invalid path.
Thus to make the plugin work as before the commit,
take only the first line of the results.

## Description

Add `head -n 1` to filter out the rest of the result except the first line.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by gaelicWizard — APPROVED** [review]
LGTM!

**Comment by tsiflimagas** [comment]
Perhaps you could do the same with just grep, instead of adding another pipeline, by adding `-m1` to the options, to stop matching after the first match.

**Comment by NariyasuHeseri** [comment]
> Perhaps you could do the same with just grep, instead of adding another pipeline, by adding `-m1` to the options, to stop matching after the first match.

Great advice.
I have updated my PR.

**Review by NoahGorny — APPROVED** [review]
Well done @NariyasuHeseri !
Maybe we should add tests for this? we can achieve this by adding mock `upower` and `acpi` functions with pre-generated output

**Comment by NariyasuHeseri** [comment]
> Well done @NariyasuHeseri ! Maybe we should add tests for this? we can achieve this by adding mock `upower` and `acpi` functions with pre-generated output

For now I cannot come up with an easy way to do that in the current testing framework since the problem is caused by a subshell expansion where the subshell also uses upower but with --enumerate option.
Any good ideas?

**Comment by gaelicWizard** [comment]
@NariyasuHeseri, the multiple lines come up when there's multiple batteries? 

Alsö, a mocked `upower` function does *not* need to be comprehensive. Within the context of unit testing, the mock needs to be *barely* adequate. So, for example:
```bash
function upower() {
  case $1 in 
    '-e') echo "the string for BAT to match" ;;
    '-I') printf "voltage:             12.191 V\n    time to full:        57.3 minutes\n    percentage:          %s\n    capacity:            84.6964" "${percent}" ;;
  esac
}
```

**Comment by NariyasuHeseri** [comment]
> @NariyasuHeseri, the multiple lines come up when there's multiple batteries?

As far I can tell, my bluetooth mouse shows up in the result of `upwer --ernumerate` with a pathname like `/org/freedesktop/UPower/devices/mouse_hid_xxxxxxxxxxxxx_battery`,
thus grep -i BAT does not filter this out.

**Comment by NariyasuHeseri** [comment]
> Alsö, a mocked `upower` function does _not_ need to be comprehensive. Within the context of unit testing, the mock needs to be _barely_ adequate. So, for example:
> 
> ```shell
> function upower() {
>   case $1 in 
>     '-e') echo "the string for BAT to match" ;;
>     '-I') printf "voltage:             12.191 V\n    time to full:        57.3 minutes\n    percentage:          %s\n    capacity:            84.6964" "${percent}" ;;
>   esac
> }
> ```
> 
> There's already mock `upower` and `acpi` functions in the tests.

The bug is cause by that concatenating multiple paths results in an invalid path,
so the example does not seem to capture the bug.

Also, IMHO, as long as mocking is used,
any test covering this bug relies on the implementation detail that `upower --enumerate` is called and its result is fed to `upower --show-info`,
which I'm not sure is good practice.

**Comment by gaelicWizard** [comment]
For unit testing, dependency injection is *expressly* best practice. Unless we are testing the `upower` binary itself, we should mock it. We definitely don't want the tests to pass or fail based on which system we're running them on; they should fail everywhere if we fail to handle an edge case. The automated testing, for example, runs on virtual machines with no batteries. 

The goal of mocking is to produce known-problematic examples so that we can test that *our* code handles it properly every time. We should add as many such examples as we find! 

So, e.g., add two paths for `upower -e` from our mock. If any future change fails to handle multiple results properly, then the test fails. 

I don't have any `upower` handy, so I'd be happy to expand our mocked function if you (or anyone) could post a couple examples of output?

**Comment by gaelicWizard** [comment]
Ok, I did a update for the tests in NariyasuHeseri/bash-it#1. How's that look?

**Comment by gaelicWizard** [comment]
I do think there's work to be done so we're not discarding one of the batteries randomly, which we didn't even know we were doing previously. But how to determine which battery is "best"?

**Comment by NariyasuHeseri** [comment]
> Ok, I did a update for the tests in [NariyasuHeseri#1](https://github.com/NariyasuHeseri/bash-it/pull/1). How's that look?

Thanks very much for adding tests to my PR.
Your PR (https://github.com/NariyasuHeseri/bash-it/pull/1) modified the line `local command_output="no"` to `local command_output="no" batteries`,
which looks like a typo.
Can you confirm that?

**Comment by NariyasuHeseri** [comment]
> I do think there's work to be done so we're not discarding one of the batteries randomly, which we didn't even know we were doing previously. But how to determine which battery is "best"?

On my computer, after running `upower --enumerate`,
 the pathname of the primary battery is shown as `/org/freedesktop/UPower/devices/battery_BAT0`.
What does the pathname become on other distros or MacOS?

**Comment by NariyasuHeseri** [comment]
> Ok, I did a update for the tests in [NariyasuHeseri#1](https://github.com/NariyasuHeseri/bash-it/pull/1). How's that look?

I have checked out your PR (https://github.com/NariyasuHeseri/bash-it/pull/1) and run the tests,
but the result is

```
 ✓ plugins battery: battery-percentage with no tool
 ✓ plugins battery: battery-percentage with pmset, 100%
 ✓ plugins battery: battery-percentage with pmset, 98%
 ✗ plugins battery: battery-percentage with pmset, 98.5%
 ✓ plugins battery: battery-percentage with pmset, 4%
 ✓ plugins battery: battery-percentage with pmset, no status
 ✓ plugins battery: battery-percentage with acpi, 100% Full
 ✓ plugins battery: battery-percentage with acpi, 98% Charging
 ✓ plugins battery: battery-percentage with acpi, 98% Discharging
 ✓ plugins battery: battery-percentage with acpi, 98% Unknown
 ✓ plugins battery: battery-percentage with acpi, 4% Charging
 ✓ plugins battery: battery-percentage with acpi, 4% no status
 ✓ plugins battery: battery-percentage with acpi, no status
 ✗ plugins battery: battery-percentage with upower, 100%
 ✗ plugins battery: battery-percentage with upower, 98%
 ✗ plugins battery: battery-percentage with upower, 98.5%
 ✗ plugins battery: battery-percentage with upower, 4%
 ✓ plugins battery: battery-percentage with upower, no output
 ✓ plugins battery: battery-percentage with ioreg, 100%
 ✓ plugins battery: battery-percentage with ioreg, 98%
 ✗ plugins battery: battery-percentage with ioreg, 98.5%
 ✓ plugins battery: battery-percentage with ioreg, 4%
 ✓ plugins battery: battery-percentage with ioreg, no status
 ✓ plugins battery: battery-percentage with WMIC, 100%
 ✓ plugins battery: battery-percentage with WMIC, 98%
 ✗ plugins battery: battery-percentage with WMIC, 98.5%
 ✓ plugins battery: battery-percentage with WMIC, 4%
 ✓ plugins battery: battery-percentage with WMIC, no status

28 tests, 7 failures
```

**Comment by gaelicWizard** [comment]
> `local command_output="no" batteries`,
> 
> which looks like a typo.
> 
> Can you confirm that?

I added a local variable `batteries` so that we don't hide one of the `upower` invocations inside a string expansion.

**Comment by gaelicWizard** [comment]
> What does the pathname become on other distros or MacOS?

There is no `upower` on Mac, and I don't have any Linux handy at the moment.

**Comment by gaelicWizard** [comment]
> newly added tests do not seem to pass

Second try coming up next! 😃

**Comment by gaelicWizard** [comment]
The test failure was due to grep -o '[0-9]\+' being different than grep --max-count=1 -o '[0-9]\+'... does not make sense to me, but I guess it's `grep`'s way of printing a single line with multiple matches...

**Comment by NariyasuHeseri** [comment]
@gaelicWizard Thanks for updating your PR.
But now all tests pass even if `--max-count=1` is removed (because `upower --show-info` is mocked and does not check validity of the pathname).

**Comment by gaelicWizard** [comment]
@NariyasuHeseri, try now?

I've added an explicit check for whether the argument provided is actually the one returned.

**Comment by NariyasuHeseri** [comment]
> @NariyasuHeseri, try now?
> 
> I've added an explicit check for whether the argument provided is actually the one returned.

Looks good.
I've merged the PR on my repo.

**Comment by NariyasuHeseri** [comment]
@NoahGorny Perhaps it's time to merge this PR?

**Review by NoahGorny — APPROVED** [review]
Alright, let's merge. @gaelicWizard is this ready?

**Comment by gaelicWizard** [comment]
![https://media1.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif?cid=82a1493bcxuo3iwnjunjflk1vkdk984wzwxsb3qvs73kg1q1&rid=giphy.gif&ct=g]

**Comment by NariyasuHeseri** [comment]
@NoahGorny Let's merge?

**Review by cornfeedhobo — APPROVED** [review]

**Pull request merged**
