### PR TITLE
Cleanup for modern theme

### PR DESCRIPTION
**Pull request by tiagobarros99**
## Description

Lint and cleanup for the `modern.theme.bash` | PR: #1812

## How Has This Been Tested?

Ran the `lint_clean_files.sh`
One issue arised, which i asked input for, on line 49

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [X] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Review by NoahGorny — APPROVED** [review]
LGTM

**Comment by NoahGorny** [comment]
@tiagobarros99 fix the conflicts and I will merge :smile:

**Comment by tiagobarros99** [comment]
Hey @NoahGorny , I just have one question regarding the conflit merge, since I'm pretty new to pull requests.

Do I just pull from master to this branch (my master is even with  Bash-it:master), resolve the conflits, and push the changes? That won't clutter the commit history or do anything funny?

**Comment by NoahGorny** [comment]
> Hey @NoahGorny , I just have one question regarding the conflit merge, since I'm pretty new to pull requests.
> 
> Do I just pull from master to this branch (my master is even with Bash-it:master), resolve the conflits, and push the changes? That won't clutter the commit history or do anything funny?

The correct way to do that would be to use `git rebase`. You should rebase your branch on top of master, and fix conflicts as they come. This will get rid of the annoying `merging "master" to "branch"` commits. If you are encountering trouble with `git rebase`, dont be afraid to ask for help :smile:

**Comment by tiagobarros99** [comment]
Sorry for the delay, I was reading about `git rebase` to make sure I did it right ahah.
Thanks for the help!

**Pull request merged**
