### PR TITLE
Adds history + command line number to powerline themes

### PR DESCRIPTION
**Pull request by davidpfarrell**
Adds 2 new segments to the powerline themes to show the history number or the command number.

I'm not sold on either the default color nor the default character and would be happy to discuss alternatives.

-DF

### CODE REVIEW

**Comment by nwinkler** [comment]
This one seems to be next... Can you please rebase?

**Comment by davidpfarrell** [comment]
> This one seems to be next... Can you please rebase?

Done, thank you !

**Comment by davidpfarrell** [comment]
Moving the PR list along as we go :)

1)  ~~#1448 "Makes all powerline vars configurable"~~
2) ~~#1450 "Fixes prompt bg color on powerline naked theme"~~
3) ~~#1446 "Adds SHORT_USER/HOSTNAME support to powerline themes"~~
4) ~~#1443 "Adds shlvl segment to powerline themes"~~
5) ~~#1442 "Adds dirstack segment to powerline themes"~~
6) #1444 "Adds history + command line number to powerline themes"
7)  ~~#1445 "Adds soft-separator support to powerline main + multiline themes"~~
8) #1449 "Adds last segment prompt char to powerline default theme"
9) #1447 "Adds compact support to powerline themes"

**Comment by nwinkler** [comment]
Thanks, merged!

**Pull request merged**
