### PR TITLE
Add mkcd and del functions

### PR DESCRIPTION
**Pull request by mimoralea**
The mkcd function creates a directory and changes the current directory into it.
The del function moves the file or folder into a hidden folder in the tmp directory, the tmp directory will get cleared on shutdown as it does by default.

### CODE REVIEW

**Comment by mimoralea** [comment]
I think you asked me to add a comment to a pull request in order to get notified...

**Comment by nwinkler** [comment]
There already is a `mkcd` function defined in the `base` plugin, which does the same thing: https://github.com/Bash-it/bash-it/blob/master/plugins/available/base.plugin.bash#L84

I don't think we have a `del` function yet, but I think it should be placed into the `base` plugin as well, as we have a collection of general functions there.

Sorry to say, but I suggest you remove the duplicate `mkcd` function...

**Comment by mimoralea** [comment]
Sure, no worries. Interesting I didn't find it. Maybe I don't have that plugin enabled. I will check in few days and get the correct patch up. Thanks!

**Comment by mimoralea** [comment]
Sorry for the delay!

**Comment by nwinkler** [comment]
Cool - thanks for taking the time to tidy this up!

**Pull request merged**
