### PR TITLE
Toggle able commit count

### PR DESCRIPTION
**Pull request by zhao-li**
If there's a better way of handling the test setup, then please let me know. 😀

### CODE REVIEW

**Comment by zhao-li** [comment]
Hi, just checking back to see if there's anything else I can add to this pull request or if it's not something that will be merged.  Thanks :)

**Comment by nwinkler** [comment]
Looks good - could you please add some documentation in the README file to describe the new parameter?

**Comment by zhao-li** [comment]
Okay, I took my best stab at documenting this.  I'm not quite sure where this detail should be added in the whole grand scheme of the README.  Please let me know what you think.

**Comment by nwinkler** [comment]
Looks good to me - thanks for adding the documentation that I requested!

**Comment by zhao-li** [comment]
Thank you for the suggestion and merging. I can't wait to start using the option. 😁👍🏻

**Pull request merged**
