### PR TITLE
Create the changelog of git commits by date

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description
Creates the git changelog 

## Motivation and Context

It is a handy tool to create the changelog by dates. It supports both markdown and plain text export

## How Has This Been Tested?

I have tested this on a live project I have been working for an year now. It is working fine.

## Screenshots (if appropriate):

image

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by NoahGorny** [comment]
@tbhaxor can you also split here for a new git changelog func and the linting into separate PRs? both are awesome btw :smile:

**Comment by cornfeedhobo** [comment]
> @tbhaxor can you also split here for a new git changelog func and the linting into separate PRs? both are awesome btw

Another trick is to split up the linting into different commits, that way we can look at each commit's diff and make sense of what you were trying to achieve.

**Comment by tbhaxor** [comment]
Sure, will do this weekend and update the pull req :smile:

**Comment by tbhaxor** [comment]
> @tbhaxor can you also split here for a new git changelog func and the linting into separate PRs? both are awesome btw

@NoahGorny  You want to me separate this https://github.com/Bash-it/bash-it/pull/1755/commits/87c539584935be05e4c111fcaa73f66011eae5eb ?

**Comment by NoahGorny** [comment]
> 
> 
> > @tbhaxor can you also split here for a new git changelog func and the linting into separate PRs? both are awesome btw
> 
> @NoahGorny You want to me separate this [87c5395](https://github.com/Bash-it/bash-it/commit/87c539584935be05e4c111fcaa73f66011eae5eb) ?

No, I am saying that your PR does cleanup and adds a new feature at the same time. I want you to separate the changes so I could review them separately. By the way, in your cleanup PR, please add the git plugin file to `clean_files.txt` to fully lint it.

Thanks for going through this!

**Pull request closed without merging**
