### PR TITLE
adding datetime and battery percentage to theme 'bobby'

### PR DESCRIPTION
**Pull request by goromlagche**
`bobby` is my favourite theme on `bash-it`, but it does not have `time` on prompt, which is important.

### CODE REVIEW

**Comment by nwinkler** [comment]
For the sake of being backwards-compatible, it would probably make sense to make this feature optional. Maybe add an environment variable like `THEME_SHOW_TIME` (default value: `false`). If people want to enable the time, they can set this variable in their profile.

**Comment by edubxb** [comment]
Totally agree with @nwinkler, this should be optional.

**Comment by goromlagche** [comment]
ok cool, so I added the checks, and made some more changes

1. added `datetime` instead of `time`
2. also added `battery_percentage` to the prompt.

All these are by default enabled.

**Comment by nwinkler** [comment]
Could you make the following changes?

* `BATTER_PERCENTAGE_CHECK` should be `THEME_BATTERY_PERCENTAGE_CHECK`: I would like to use the `THEME` prefix for things like this, and the name should refer to a battery, we're not trying to bake a cake :smile: 
* `CLOCK_CHECK` should be `THEME_CLOCK_CHECK`

**Comment by goromlagche** [comment]
@nwinkler fixed(prefixed) it  :smile:

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
