### PR TITLE
Added alias that only list top level modules

### PR DESCRIPTION
**Pull request by ycmjason**
Credits to our mighty Evan You (creator of Vue.js) @yyx990803

https://gist.github.com/yyx990803/6045243

### CODE REVIEW

**Comment by ycmjason** [comment]
Well the alias name is not good as `nl` overwrites the command `nl`...

I am tempted to replace the the already existing `nls` and `nlsg` with this shallow listing, which makes more sense.

**Comment by nwinkler** [comment]
How about `npl` and `nplg`? Or `npml` and `npmlg`? Both are still a good deal shorter than typing the full commands...

**Comment by ycmjason** [comment]
Yes make sense. Will put those changes

**Comment by ycmjason** [comment]
I sincerely think that `nls` and `nlsg` belongs to this shallow listing.

**Comment by nwinkler** [comment]
What makes you think that? Wouldn't that break the existing functionality for people who are already using `nls` and `nlsg`?

**Comment by ycmjason** [comment]
This is simply because `npm list` shows the complete list of all dependencies recursively. This means for any decent sized project, it can easily contain >1000 lines of dependencies. This is not very useful information. What developers care about most of the time is the root dependencies of a project, without diving into dependencies' dependencies.

**Comment by nwinkler** [comment]
Thanks for the explanation. I understand the difference between the long and the short listing, but I guess the "not very useful information" is rather subjective. 

While I agree that the shorter listing might be more useful, I'm just afraid that we're changing existing functionality that was working differently before.

We can give it a try and see if people start complaining about the change. I'm all for making things simpler and easier to digest...

**Comment by ycmjason** [comment]
Thank you for understanding and the approval of replacing the current command. Let us give it a try and if people complain, please let me know and I would be happy to switch it back out for `npml` and `npmlg`.

**Comment by ycmjason** [comment]
@nwinkler any update on this?

**Comment by nwinkler** [comment]
Sorry, have been busy with some other work... Thanks again for the contribution!

**Pull request merged**
