### PR TITLE
Migrate wiki docs to rtd format

### PR DESCRIPTION
**Pull request by NoahGorny**
Another important step after #1688

### CODE REVIEW

**Comment by nwinkler** [comment]
My main question for this PR is how/where we're going to maintain the theme screenshots. At the moment, they're in the Wiki, and the `.rst` file references the files hosted on GitHub's wiki location. Do we want to keep doing that? That means we'll still have to upload new screenshots to the Wiki and then refer to them in the `.rst` file.

What I would like to avoid is adding screenshots to the Git repo as part of the main branches, since that will blow up the size of the repo unnecessarily. The Wiki works well for that, but it introduces the above dependency and makes the process more difficult.

Thoughts?

**Comment by cornfeedhobo** [comment]
This is tough. screenshots are the eyecandy that draw most users in to start, but I too dislike them. I think my vote is to trash them...

**Comment by NoahGorny** [comment]
I think we should recommend new contributors to store their image on some free image hosting service and link, this is not ideal, but I do not want people to add big files to the repo. We can update the instructions to add a theme with that information

**Comment by davidpfarrell** [comment]
Maybe we could store them the project's [`gh-pages` (github pages)](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#:~:text=To%20publish%20a%20user%20site,github.io%20.) branch, (under a folder path like `/docs/images`) then they would be accessible via the project's page url (i.e it would likely be `bash-it.github.io/bash-it/docs/images`)  -- From there we could reference them from within the RST documents.

Thoughts?

**Comment by NoahGorny** [comment]
This is a viable solution, we need to see if it's easy for people to upload content to there/ create a PR or something.
If it's easier than uploading to some image sharing website then I'm all for it

**Comment by NoahGorny** [comment]
@nwinkler @cornfeedhobo @davidpfarrell I am continuing with this PR and with #1704   
After it is all set and done, we can create more PRs which update our docs to include more information about how to create a theme, how to run pre-commit (like #1702) and so on

**Comment by cornfeedhobo** [comment]
> Maybe we could store them the project's [`gh-pages` (github pages)](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/about-github-pages#:~:text=To%20publish%20a%20user%20site,github.io%20.) branch, (under a folder path like `/docs/images`) then they would be accessible via the project's page url (i.e it would likely be `bash-it.github.io/bash-it/docs/images`) -- From there we could reference them from within the RST documents.
> 
> Thoughts?

I like this idea.

> I am continuing with this PR and with #1704
> After it is all set and done, we can create more PRs which update our docs to include more information about how to create a theme, how to run pre-commit (like #1702) and so on

@NoahGorny Is the idea to delete the wiki pages after this is merged?

**Comment by NoahGorny** [comment]
I think I will delete most of the wiki, and redirect users to our readthedocs. I think I will keep the theme screenshots page, just to save the pictures, and maybe make the wiki read-only if this is possible

**Comment by NoahGorny** [comment]
I have migrated our screenshots to `gh-pages` branch, and updated the docs to look at the `gh-pages` source instead of the wiki. I will edit the wiki to notify users that it is deprecated, and that they should use `readthedocs` instead

**Pull request merged**
