### PR TITLE
plugins: Fix quotes around prec_word agruments

### LINKED ISSUE #1625: Small problem in alias completion plugin.
https://github.com/Bash-it/bash-it/blob/e0dba9356186954a7393363d753be37939630f85/plugins/available/alias-completion.plugin.bash#L74

I have a alias like this:
```shell
git log --graph --date=short --pretty=format:"%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s"
```
It will show a concise and colorful log list of git.
Quote signs and brackets are used in this alias definition.

It will cause the syntax error in the plugin, like:
```text
-bash: /tmp/alias_completion-4451LTv9qp: line 813: syntax error near unexpected token `('
-bash: /tmp/alias_completion-4451LTv9qp: line 813: `                            prec_word="git log --graph --date=short --pretty=format:"%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s""'
```

### PR DESCRIPTION
**Pull request by NoahGorny**
Resolves #1625

I think this solution is working well

### CODE REVIEW

**Comment by nwinkler** [comment]
The example in #1625 uses double quotes in the problematic alias - would your solution also work with aliases with single quotes, e.g. 

```bash
git log --graph --date=short --pretty=format:'%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s'
```

Ideally, we would have a set of unit tests for the `alias-completion` plugin that tests these various scenarios. We don't have to test the full plugin, but the initialization with various alias patterns would be nice as a starting point...

**Comment by NoahGorny** [comment]
It seems like it works well even with single quotes.
I will try to add tests though, good idea

**Comment by NoahGorny** [comment]
> 
> 
> The example in #1625 uses double quotes in the problematic alias - would your solution also work with aliases with single quotes, e.g.
> 
> ```shell
> git log --graph --date=short --pretty=format:'%C(auto)%h %Cgreen%an%Creset %Cblue%cd%Creset %C(auto)%d %s'
> ```
> 
> Ideally, we would have a set of unit tests for the `alias-completion` plugin that tests these various scenarios. We don't have to test the full plugin, but the initialization with various alias patterns would be nice as a starting point...

After trying for some time, I did not manage to test this properly :cry:
tried to create an alias with double quotes and reload the alias-completion, but I could not get it to work
help would be appreciated @nwinkler

**Comment by NoahGorny** [comment]
I did manage to test this okay after all, it just worked in every case in WSL
On my ubuntu the test failed on master as expected :smile:

**Comment by nwinkler** [comment]
Thanks for pushing for this! Great, thanks!

**Pull request merged**
