### PR TITLE
Added git plugin to restore deleted file

### PR DESCRIPTION
**Pull request by tbhaxor**
## Description

Most of the time we get frustrated with the deleted files changes in the git. I have added a plugin `git_restore_file <FILE PATH>` to restore the file from HEAD

## How Has This Been Tested?

I have tested this on one of my live application, it is working fine

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by tbhaxor** [comment]
@NoahGorny Why the test is failing for this. Could you help me in fixing this PR?

**Comment by NoahGorny** [comment]
hi @tbhaxor, can you explain how exactly you should use this function? I could not use it to restore deleted files as I expected 😢

**Comment by tbhaxor** [comment]
> hi @tbhaxor, can you explain how exactly you should use this function? I could not use it to restore deleted files as I expected

So suppose you have deleted a file using `git rm -rf` then it will lookup the last revision for that file and then restore the file from that commit.

My Team member had removed a file from the production server and the clients we so angry. So by using this command I managed to restore the file in less than a minute.

**Comment by tbhaxor** [comment]
> I could not use it to restore deleted files as I expected

Execute it in the same branch where you committed file deletion

**Comment by tbhaxor** [comment]
The catch is if the file is deleted from the index, there will no further commit added to it.

So the last commit will always be of file deletion

**Comment by NoahGorny** [comment]
this does not work as expected for me- so I am closing :sob:

**Pull request closed without merging**
