### PR TITLE
Wholesale cleanup of all history plugins

### PR DESCRIPTION
**Pull request by cornfeedhobo**
## Description
- remove the use of redundant cite
- minor cleanups to history.plugin.bash
- set explicit load orders for history-search and history-substring-search
- add new plugin history-eternal

## Motivation and Context
history plugins needed some love now that we have dealt with preexec

## How Has This Been Tested?
locally

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [ ] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by cornfeedhobo** [comment]
@NoahGorny I have absolutely no idea why doc generation is failing. Could you take a look? Thanks!

**Comment by NoahGorny** [comment]
hi @cornfeedhobo, I filed #1984 to fix this failure :smiley:

**Comment by cornfeedhobo** [comment]
@NoahGorny @gaelicWizard alright, have a look

**Review by NoahGorny — APPROVED** [review]
nice work :)

**Comment by tsiflimagas** [comment]
Shouldn't `trap` be kept in the history plugin to restore `HISTTIMEFORMAT`, if it is set?

**Comment by cornfeedhobo** [comment]
@tsiflimagas great catch!
@NoahGorny Sorry I'll need one more here. Thanks in advance.

**Comment by cornfeedhobo** [comment]
I'm gonna rebase. I don't get why it's _my_ PR that keeps catching unrelated linting issues.

**Pull request merged**
