### PR TITLE
Added first draft of contribution guidelines

### PR DESCRIPTION
**Pull request by nwinkler**
@edubxb @tswicegood Please feel free to review/add/change...

I've tried to summarize a couple of common rules and guidelines, nothing too fancy.

### CODE REVIEW

**Comment by nwinkler** [comment]
From @edubxb in #644:

> Great work, fantastic!

> I agree with all the text, except the function naming, IMHO, the underscore character "_" is more readable than the dash character "-", also the underscore usage is more common in Shell scripting.

> Some related links:

> * http://wiki.bash-hackers.org/scripting/style
> * https://google.github.io/styleguide/shell.xml

> What do you think?

**Comment by nwinkler** [comment]
@tswicegood and I had a previous discussion on this in #403 - please take a look at the comments there. I was arguing along the same lines there, we'll just have to make a decision for one or the other, and then decide how we want to handle the existing codebase.

**Comment by tswicegood** [comment]
Since y'all are :+1: for `_`, I'm happy to do that. I would like to maintain BC for any functions that are changed. Maybe something like wrapping the function with function that outputs to `stderr` and notes a warning and provides the new name.

**Comment by edubxb** [comment]
Sorry @nwinkler, I wrote the comment in the wrong thread.

Another point of discussion is the "private" functions, in some places one underscore is used, and in others two, I personally prefer to use two.

The imported code (like some completion scripts) would leave it as it is, I would not change it.

I offer myself to rewrite the code to follow the guidelines chosen.

**Comment by nwinkler** [comment]
Sounds good, @edubxb.

How do we want to handle the rewrite? Change the functions to make them all use the same syntax, define _warning_ wrapper functions like @tswicegood suggested?

**Comment by edubxb** [comment]
Mmm, a full rewrite is enough, IMO, wrapping the old functions is not necessary, all the dependencies are in the repo, so the possibility to break things is low or none, I think.

**Comment by nwinkler** [comment]
The wrapper functions would be targeted at end users to make them aware of the new syntax, I guess...

**Pull request merged**
