### PR TITLE
EditorConfig: set `function_next_line`

### PR DESCRIPTION
**Pull request by gaelicWizard**
## Description
Enable `function_next_line`, which is part of the default settings for `shfmt` and which most of this repo already uses.

## Motivation and Context
Linters and formatters are good; they make tedium easy. But, they need to be configured properly. So. Yeah.

## References
The `.editorconfig` file initially checked in to _Bash It_ was copied from an earlier version of the [`shfmt` man page]( https://www.mankier.com/1/shfmt#Examples ). The current version includes `function_next_line = true  # like -fn`, which much of this repository already uses.

## How Has This Been Tested?
Testing? Where we're going, we don't need testing!

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by NoahGorny** [comment]
seems like you need to fix some things after this change (probably the function-next-line one)

**Comment by gaelicWizard** [comment]
Ok, I've finished pushing everything.

**Review by NoahGorny — APPROVED** [review]
Lgtm, I am okay with making this cosmetic change in the repo, although I didn't have too much problem with the old look as well

**Comment by davidpfarrell** [comment]
Hi Team !

@gaelicWizard could you link some some documentation/discussion regarding `function_next_line` and `shftm` ?

I am not sold on the idea and a quick googling has not turned up any confirmation (ie style guides or strong public opinion) on the concept.

I prefer same line and again, haven't seen a style guide that suggests otherwise.

Thanks!

-DF

**Comment by gaelicWizard** [comment]
@davidpfarrell, in hindsight that *definitely* should have been a separate PR. I've made a new one for *just* the fix to the tab setting that I broke.

For `function_next_line`:
The `.editorconfig` file initially checked in to _Bash It_ was copied from an earlier version of the [`shfmt` man page]( https://www.mankier.com/1/shfmt#Examples ). The current version includes `function_next_line = true  # like -fn`, which much of this repository already uses.

It doesn't make sense to me to change from what's already common throughout the repo to a slightly different format that is syntactically identical. It makes more sense to me that opening and closing scopes should be *visually* apparent, but I would not have proposed this if I didn't see so much code already in this format. In particular, there are a lot of scope-related mistakes (mostly harmless) that I keep running across, so I think it's helpful for scopes to be more easily visible.

I am absolutely on the "test, lint, and test again" bandwagon, but it seems like the testing/linting for _Bash It_ was checked in "just to get something set up". This is better than not! But, it wasn't fully configured and I don't think it should be held back by early assumptions.

**Comment by gaelicWizard** [comment]
@davidpfarrell, @NoahGorny I'd actually like to disable the `shfmt` test for now. I think it's more trouble than it's worth at this time. (I absolutely love `shellcheck`.)

**Comment by NoahGorny** [comment]
> @davidpfarrell, @NoahGorny I'd actually like to disable the `shfmt` test for now. I think it's more trouble than it's worth at this time. (I absolutely love `shellcheck`.)

Why would you want to do that?
I find it similar to `black`. It forces you to have a specific style, unified across the entire project (currently it's only partial, but I hope that we will be able to lint all files in the future)

**Comment by gaelicWizard** [comment]
> > @davidpfarrell, @NoahGorny I'd actually like to disable the `shfmt` test for now. I think it's more trouble than it's worth at this time. (I absolutely love `shellcheck`.)
> 
> Why would you want to do that?
> I find it similar to `black`. It forces you to have a specific style, unified across the entire project (currently it's only partial, but I hope that we will be able to lint all files in the future)

I do agree with standardising the code style, but it doesn't do that the way it's currently set up. The requirements as configured don't match what most of the code is. 

Maybe a better way to say this would be to separate `shellcheck` from `shfmt` tests. `shfmt` is purely for the programmer; it just makes things look one way or another, to help us read/write code. `shellcheck` looks for actual/potential problems where the code doesn't work or doesn't do what it seems. 

I'm OK with a decision to keep `shfmt` enabled, and I'll make peace with keeping scope indicators on the wrong line, but I'd just really like it to be consistent. At least 60% of my effort getting PRs approved has been due to these sorts of things! Oy!

**Comment by davidpfarrell** [comment]
Hi All, 

So i've been grinding on it an I'm just not into the open-brace-on-next-line style.

Regardless of personal style, I don't think the change brings enough value.

In the presence of automated formatting tools, whatever style we decide on will be automatically managed, BUT ...

I've done a second google search for bash style guides and reviewed over a dozen, and *none* of them recommended this style.

Apologies, but I'm just not in favor of this PR ...

**Comment by cornfeedhobo** [comment]
I thought we already discussed the opposite convention of _not_ placing braces on the newline. I can't find the issue though.

**Comment by cornfeedhobo** [comment]
> The requirements as configured don't match what most of the code is.

@gaelicWizard This was the intent behind `clean_files.txt`, to iterate and improve everything slowly, and track what's already been complete. We decided that a wholesale cleanup all at once introduces way too many changes to backtrack errors from. We've accepted the slow pace.

**Pull request closed without merging**
