### PR TITLE
add bulk enable or disable function

### PR DESCRIPTION
**Pull request by crazygit**

### CODE REVIEW

**Comment by nwinkler** [comment]
Thanks for the contribution! Before this is merged - could you please add some documentation on how to use this?

**Comment by crazygit** [comment]
@nwinkler Add doc, please check it.

**Comment by nwinkler** [comment]
Ah, great! Could you please also add it to the help messages in https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash#L137 and https://github.com/Bash-it/bash-it/blob/master/lib/helpers.bash#L139?

**Comment by crazygit** [comment]
Sorry for missing, already added it.

**Comment by nwinkler** [comment]
Sorry about the back and forth - but there's one more thing :smile: 

The completion for the `bash-it` function (https://github.com/Bash-it/bash-it/blob/master/completion%2Favailable%2Fbash-it.completion.bash) does not support the new extended bulk functionality yet.

If I do this, the completion shows the available (not-enabled) plugins:

```bash
bash-it enable plugin <TAB><TAB>
```

This works fine for the first plugin. Once I have selected that, and try to enable another one in the same call:

```bash
bash-it enable plugin tmux <TAB><TAB>
```

it stops working. Instead of showing me the other plugins that I could enable, it's showing me `disable enable help show` again.

Could you take a look at the completion function I linked above and see if you can add support for the bulk parameters?

**Comment by crazygit** [comment]
@nwinkler added completion function

**Comment by thedrow** [comment]
LGTM. @nwinkler Merge?

**Comment by nwinkler** [comment]
Sorry - didn't have time to check into this (traveling). I'll take a look now...

**Comment by nwinkler** [comment]
Works fine for me, thanks for the contribution!

**Comment by edubxb** [comment]
Wow, great improvement! Thanks @crazygit!

**Pull request merged**
