### PR TITLE
Creates my custom theme.

### PR DESCRIPTION
**Pull request by TheNinJedi**
I wanted a different prompt than was available. I will likely make changes to it as I go along. Refine it.

### CODE REVIEW

**Comment by nwinkler** [comment]
Care to share a screenshot?

**Comment by TheNinJedi** [comment]
sure. Do you know if there is a tool I can use to anonymize my prompt so that it doesn’t reflect my name or my project I am working on but will still show off the features of the prompt?

**Comment by the-undefined** [comment]
I can help out there, I don't mind sharing my prompt:

screen shot 2015-10-02 at 05 23 18

One improvement I would suggest would be to intorduce a space after the `$` a the end of the prompt: `$cd ..` VS `$ cd ..`.

**Comment by TheNinJedi** [comment]
Thank You!

**Comment by NoahGorny** [comment]
This PR has gone stale, so I am closing it. Thanks for contributing!

**Pull request closed without merging**
