### PR TITLE
Fixed spelling and wording

### PR DESCRIPTION
**Pull request by nwinkler**
Some minor changes in spelling, wording and formatting.

### CODE REVIEW

**Comment by edubxb** [comment]
Thanks!, I need to improve my english :P

**Comment by tswicegood** [comment]
@edubxb your English skills are a lot better than my ``{{ insert any other language }}` skills! It's awesome having you participate in this project!! The powerline theme is the only one that I've kept using for more than a month or two. :-)

**Comment by edubxb** [comment]
Thanks for your words @tswicegood!

I appreciate a lot the great work that @nwinkler is doing, I can't dedicate the time that I'd like to the project.

**Comment by nwinkler** [comment]
You're welcome! I spend a lot of time on the train on my way to work...

Your English is great, don't worry.

**Pull request merged**
