### PR TITLE
migrate to github actions

### PR DESCRIPTION
**Pull request by NoahGorny**
- Add github action to replace travis

Tested on my fork, works great (could not get caching to work.. not a must anyway)

### CODE REVIEW

**Comment by NoahGorny** [comment]
@cornfeedhobo @davidpfarrell @nwinkler I want to merge this today so we will have pipelines asap, please take a look if you can

**Comment by cornfeedhobo** [comment]
@NoahGorny is the goal to get rid of travis at a later date?

**Comment by NoahGorny** [comment]
> @NoahGorny is the goal to get rid of travis at a later date?

Yes, as currently it has stopped working entirely. We can remove the configuration in another PR

**Review by cornfeedhobo — APPROVED** [review]

**Comment by cornfeedhobo** [comment]
I didn't notice travis being broken. What happened?

**Comment by NoahGorny** [comment]
> ~I didn't notice travis being broken. What happened?~
> 
> > Builds have been temporarily disabled for public repositories due to a negative credit balance.
> 
> lol. yeah, that's not going to happen. GitHub Actions it is!
> 
> P.S. this might be an issue as PR counts grow

This is not problematic for GitHub actions as they offer infinite runtime for open source projects :smile:

**Pull request merged**
