### PR TITLE
Update .gitmodules

### PR DESCRIPTION
**Pull request by georgettica**
## Motivation and Context

Currently on my machine bash-it update fails because of this.

I hope.this change will make it pass.
## How Has This Been Tested?

It has not, trying to see if the CI will pass
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] If my change requires a change to the documentation, I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] If I have added a new file, I also added it to ``clean_files.txt`` and formatted it using ``lint_clean_files.sh``.
- [x] I have added tests to cover my changes, and all the new and existing tests pass.

### CODE REVIEW

**Comment by georgettica** [comment]
Seems this change has the CI pass :)

So it's worth just merging it IMO

**Comment by georgettica** [comment]
Seems he tests only start at 16, do you know why?

**Comment by tbhaxor** [comment]
The fix is already in progress https://github.com/Bash-it/bash-it/pull/2117

**Review by tbhaxor — APPROVED** [review]
lgtm

**Comment by georgettica** [comment]
Thanks!
Will close and follow it :)

**Pull request closed without merging**
