### PR TITLE
Templates

### PR DESCRIPTION
**Pull request by tbhaxor**
Fix issue: #1335

### CODE REVIEW

**Comment by tbhaxor** [comment]
I have created a basic template for pull request and issue
Since i dnt know what you want from collaborators to be strictly followed so please edit it after merging

Thankx

**Comment by tbhaxor** [comment]
@nwinkler Kindly review this PR !

**Comment by nwinkler** [comment]
@tbhaxor Thanks for providing these. I'll review these when I have some time - hopefully on the weekend. They look like a good starting point, but I can already see some changes that I want to make - I'll need some more time for that.

**Comment by tbhaxor** [comment]
@nwinkler  No issue. I thought i should remind you :laughing:

**Pull request closed without merging**
