### PR TITLE
Ignore untracked files

### PR DESCRIPTION
**Pull request by edubxb**
Add the flag `SCM_GIT_IGNORE_UNTRACKED` to ignore *untracked* files in git prompt.

### CODE REVIEW

**Comment by edubxb** [comment]
Closes https://github.com/Bash-it/bash-it/pull/342 and https://github.com/Bash-it/bash-it/pull/384

**Comment by edubxb** [comment]
Closes https://github.com/Bash-it/bash-it/pull/342 and https://github.com/Bash-it/bash-it/pull/384

**Comment by jawshooah** [comment]
> Set `SCM_GIT_IGNORE_UNTRACKED` to 'true' (the default value) to get information about *untracked* files

This seems counterintuitive. Shouldn't you set it to `true` to *ignore* untracked files, as implied by its name?

**Comment by edubxb** [comment]
Ups, sorry, the README is wrong, I will correct it.

Thanks @jawshooah!

**Comment by edubxb** [comment]
Fixed!

**Pull request merged**
