### PR TITLE
Rename http alias

### PR DESCRIPTION
**Pull request by mimoralea**
It would be nice to still have this alias but not colliding with the awesome httpie tool:

https://github.com/jakubroztocil/httpie

### CODE REVIEW

**Comment by nwinkler** [comment]
I've run into the same thing recently when I installed `httpie`. I'm not sure whether `https` is a good name, though. What do you think about something like `simplehttp`?

We should also add a check whether `http` is already defined. If it is (`httpie` is installed), then we should use a new alias, otherwise, we can keep using the `http` alias to stay backwards compatible.

What do you think?

**Comment by edubxb** [comment]
I agree with @nwinkler, `https` is not the best name.

**Comment by mimoralea** [comment]
I like the idea of checking for the binary first... let me take a look at it.

**Comment by mimoralea** [comment]
About the name, I like simplehttp, though I wanted to keep it short... shttp?

**Comment by nwinkler** [comment]
I think that would work - easy to remember, too.

**Comment by edubxb** [comment]
:+1:

**Comment by mimoralea** [comment]
Good deal. Will do that.

**Comment by nwinkler** [comment]
Thanks!

**Pull request merged**
